import type { ReactNode } from "react";

export type PrintDirection = "ltr" | "rtl";

export interface PrintMetadataItem {
  label: string;
  value: ReactNode;
}

interface PrintDocumentProps {
  title: string;
  locale: string;
  direction?: PrintDirection;
  subtitle?: string;
  metadata?: PrintMetadataItem[];
  children: ReactNode;
}

/**
 * A layout-only component for printable content. It is intentionally separate
 * from the dashboard UI so every feature has the same document header/footer
 * and locale-aware direction.
 */
export default function PrintDocument({
  title,
  locale,
  direction = locale === "ar" ? "rtl" : "ltr",
  subtitle,
  metadata = [],
  children,
}: PrintDocumentProps) {
  const printedAt = new Intl.DateTimeFormat(locale, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date());

  return (
    <article
      className="print-document"
      dir={direction}
      lang={locale}
      data-print-document
    >
      <header className="print-document__header">
        <div>
          <p className="print-document__eyebrow">
            {locale === "ar" ? "نظام إدارة المدرسة" : "School Management System"}
          </p>
          <h1>{title}</h1>
          {subtitle ? <p className="print-document__subtitle">{subtitle}</p> : null}
        </div>
        <p className="print-document__generated">
          {locale === "ar" ? "تاريخ الطباعة: " : "Printed: "}
          <bdi>{printedAt}</bdi>
        </p>
      </header>

      {metadata.length > 0 ? (
        <dl className="print-document__metadata">
          {metadata.map((item) => (
            <div key={item.label}>
              <dt>{item.label}</dt>
              <dd>{item.value}</dd>
            </div>
          ))}
        </dl>
      ) : null}

      <section className="print-document__content">{children}</section>

      <footer className="print-document__footer">
        {locale === "ar" ? "وثيقة تم إنشاؤها من النظام" : "Document generated by the system"}
      </footer>
    </article>
  );
}
