export const dashboardAnnouncementLabels = {
  en: {
    title: "Title",
    body: "Body",
    priority: "Priority",
    normal: "Normal",
    low: "Low",
    high: "High",
    urgent: "Urgent",
    audienceType: "Audience type",
    audience: "Audience",
    school: "School",
    stage: "Stage",
    grade: "Grade",
    section: "Section",
    classroom: "Classroom",
    custom: "Custom",
    searchUsers: "Search users...",
    createDraft: "Create Draft",
    draftCreated: "Announcement draft created.",
    draftFailed: "Unable to create announcement.",
    titleRequired: "Enter a title.",
    bodyRequired: "Enter a body.",
    audienceRequired: "Select an audience.",
    openFullForm: "Open full announcement form",
  },
  ar: {
    title: "العنوان",
    body: "المحتوى",
    priority: "الأولوية",
    normal: "عادية",
    low: "منخفضة",
    high: "عالية",
    urgent: "عاجلة",
    audienceType: "نوع الجمهور",
    audience: "الجمهور",
    school: "المدرسة",
    stage: "المرحلة",
    grade: "الصف",
    section: "الشعبة",
    classroom: "الفصل",
    custom: "مخصص",
    searchUsers: "ابحث عن المستخدمين...",
    createDraft: "إنشاء مسودة",
    draftCreated: "تم إنشاء مسودة الإعلان.",
    draftFailed: "تعذر إنشاء الإعلان.",
    titleRequired: "أدخل عنوانا.",
    bodyRequired: "أدخل المحتوى.",
    audienceRequired: "اختر جمهورا.",
    openFullForm: "فتح نموذج الإعلان الكامل",
  },
};

export type DashboardAnnouncementLabels =
  (typeof dashboardAnnouncementLabels)[keyof typeof dashboardAnnouncementLabels];
export type DashboardAnnouncementLocale =
  keyof typeof dashboardAnnouncementLabels;
