import type { TeacherDirectoryDetail } from "@/features/teachers/types/index";

export const teacherFixture: TeacherDirectoryDetail = {
  id: "teacher-1",
  userId: "user-1",
  loginEmail: "nour@school.example",
  username: "nour.ali",
  contactEmail: "nour@example.com",
  phone: "+201000000000",
  teacherCode: "TCH-001",
  firstNameAr: "نور",
  lastNameAr: "علي",
  firstNameEn: "Nour",
  lastNameEn: "Ali",
  displayName: { firstName: "Nour", lastName: "Ali", fullName: "Nour Ali" },
  gender: "FEMALE",
  department: "Science",
  specialization: "Biology",
  accountStatus: "ACTIVE",
  membershipStatus: "ACTIVE",
  membershipEndedAt: null,
  employmentStatus: "INACTIVE",
  profileCompleteness: { isComplete: true, missingFields: [] },
  credentialSummary: {
    hasPassword: true,
    status: "set",
    mustChangePassword: false,
    passwordProvisionedAt: "2026-07-01T08:00:00Z",
    passwordChangedAt: "2026-07-02T08:00:00Z",
    credentialVersion: 2,
  },
  employmentType: "FULL_TIME",
  experienceYears: 6,
  hireDate: "2020-08-20",
  workingDays: ["SUNDAY", "MONDAY"],
  workStartTime: "07:30:00",
  workEndTime: "14:30:00",
  notesAr: null,
  notesEn: null,
  createdAt: "2026-07-01T08:00:00Z",
  updatedAt: "2026-07-20T08:00:00Z",
};
