import {
  Home,
  Users,
  HelpCircle,
  UserPlus,
  LayoutDashboard,
  FileText,
  ClipboardCheck,
  MessageSquare,
  CheckCircle,
  GraduationCap,
  UserCheck,
  FolderOpen,
  ArrowLeftRight,
  UserMinus,
  BookOpen,
  Network,
  Clock,
  Calendar,
  ClipboardList,
  ShieldCheck,
  BellRing,
  PlugZap,
  Building2,
  Award,
  Map,
  ListChecks,
  TrendingUp,
} from "lucide-react";
import {
  mockLeads,
  mockApplications,
  mockTests,
  mockInterviews,
  mockDecisions,
} from "@/data/mockDataLinked";

interface MenuItem {
  key: string;
  label_en: string;
  label_ar: string;
  href_en: string;
  href_ar: string;
  icon: React.ComponentType<{ className?: string }>;
  children?: MenuItem[];
  badge?: () => number; // Function to get dynamic badge count
  buttonVariant?: "default" | "highlight";
  buttonBackgroundImage?: string;
}

export const menuItems: MenuItem[] = [
  {
    key: "hero-journey",
    label_en: "Hero Journey",
    label_ar: "رحلة البطل",
    href_en: "/en/hero-journey",
    href_ar: "/ar/hero-journey",
    icon: Award,
    buttonBackgroundImage: "/images/hero_journey/hero_journey_bg.svg",
  },
  {
    key: "dashboard",
    label_en: "Dashboard",
    label_ar: "لوحة المراقبة",
    href_en: "/en/dashboard",
    href_ar: "/ar/dashboard",
    icon: Home,
  },
  {
    key: "admissions-registration",
    label_en: "Admissions & Registration",
    label_ar: "القبول والتسجيل",
    href_en: "/en/admissions",
    href_ar: "/ar/admissions",
    icon: UserPlus,
    children: [
      {
        key: "admissions-dashboard",
        label_en: "Over View",
        label_ar: "نظرة عامة",
        href_en: "/en/admissions",
        href_ar: "/ar/admissions",
        icon: LayoutDashboard,
      },
      {
        key: "admissions-leads",
        label_en: "Leads",
        label_ar: "الاستفسارات",
        href_en: "/en/admissions/leads",
        href_ar: "/ar/admissions/leads",
        icon: Users,
        badge: () => mockLeads.filter((lead) => lead.status === "New").length,
      },
      {
        key: "admissions-applications",
        label_en: "Applications",
        label_ar: "طلبات الالتحاق",
        href_en: "/en/admissions/applications",
        href_ar: "/ar/admissions/applications",
        icon: FileText,
        badge: () =>
          mockApplications.filter((app) => app.status === "submitted").length,
      },
      {
        key: "admissions-tests",
        label_en: "Tests",
        label_ar: "الاختبارات",
        href_en: "/en/admissions/tests",
        href_ar: "/ar/admissions/tests",
        icon: ClipboardCheck,
        badge: () =>
          mockTests.filter((test) => test.status === "scheduled").length,
      },
      {
        key: "admissions-interviews",
        label_en: "Interviews",
        label_ar: "المقابلات",
        href_en: "/en/admissions/interviews",
        href_ar: "/ar/admissions/interviews",
        icon: MessageSquare,
        badge: () =>
          mockInterviews.filter((interview) => interview.status === "scheduled")
            .length,
      },
      {
        key: "admissions-decisions",
        label_en: "Decisions",
        label_ar: "القرارات",
        href_en: "/en/admissions/decisions",
        href_ar: "/ar/admissions/decisions",
        icon: CheckCircle,
        badge: () =>
          mockDecisions.filter((decision) => decision.decision === "waitlist")
            .length,
      },
      {
        key: "admissions-enrollment",
        label_en: "Enrollment",
        label_ar: "التسجيل",
        href_en: "/en/admissions/enrollment",
        href_ar: "/ar/admissions/enrollment",
        icon: GraduationCap,
      },
    ],
  },

  {
    key: "students-guardians",
    label_en: "Students & Guardians",
    label_ar: "الطلاب وأولياء الأمور",
    href_en: "/en/students-guardians",
    href_ar: "/ar/students-guardians",
    icon: GraduationCap,
    children: [
      {
        key: "students-guardians-dashboard",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/students-guardians",
        href_ar: "/ar/students-guardians",
        icon: LayoutDashboard,
      },
      {
        key: "students-list",
        label_en: "Students",
        label_ar: "الطلاب",
        href_en: "/en/students-guardians/students",
        href_ar: "/ar/students-guardians/students",
        icon: Users,
      },
      {
        key: "guardians-list",
        label_en: "Guardians",
        label_ar: "أولياء الأمور",
        href_en: "/en/students-guardians/guardians",
        href_ar: "/ar/students-guardians/guardians",
        icon: UserCheck,
      },
      {
        key: "documents-center",
        label_en: "Documents",
        label_ar: "المستندات",
        href_en: "/en/students-guardians/documents",
        href_ar: "/ar/students-guardians/documents",
        icon: FolderOpen,
      },
      {
        key: "transfers",
        label_en: "Transfers",
        label_ar: "التحويلات",
        href_en: "/en/students-guardians/transfers-withdrawals/transfers",
        href_ar: "/ar/students-guardians/transfers-withdrawals/transfers",
        icon: ArrowLeftRight,
        children: [
          {
            key: "transfers-overview",
            label_en: "Overview",
            label_ar: "نظرة عامة",
            href_en: "/en/students-guardians/transfers-withdrawals/transfers",
            href_ar: "/ar/students-guardians/transfers-withdrawals/transfers",
            icon: LayoutDashboard,
          },
          {
            key: "transfers-applications",
            label_en: "Applications",
            label_ar: "الطلبات",
            href_en:
              "/en/students-guardians/transfers-withdrawals/transfers/applications",
            href_ar:
              "/ar/students-guardians/transfers-withdrawals/transfers/applications",
            icon: FileText,
          },
        ],
      },
      {
        key: "withdrawals",
        label_en: "Withdrawals",
        label_ar: "الانسحابات",
        href_en: "/en/students-guardians/transfers-withdrawals/withdrawals",
        href_ar: "/ar/students-guardians/transfers-withdrawals/withdrawals",
        icon: UserMinus,
        children: [
          {
            key: "withdrawals-overview",
            label_en: "Overview",
            label_ar: "نظرة عامة",
            href_en: "/en/students-guardians/transfers-withdrawals/withdrawals",
            href_ar: "/ar/students-guardians/transfers-withdrawals/withdrawals",
            icon: LayoutDashboard,
          },
          {
            key: "withdrawals-applications",
            label_en: "Applications",
            label_ar: "الطلبات",
            href_en:
              "/en/students-guardians/transfers-withdrawals/withdrawals/applications",
            href_ar:
              "/ar/students-guardians/transfers-withdrawals/withdrawals/applications",
            icon: FileText,
          },
        ],
      },
    ],
  },
  {
    key: "academics",
    label_en: "Academics",
    label_ar: "الأكاديميات",
    href_en: "/en/academics",
    href_ar: "/ar/academics",
    icon: BookOpen,
    children: [
      {
        key: "academics-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/academics",
        href_ar: "/ar/academics",
        icon: LayoutDashboard,
      },
      {
        key: "academics-structure",
        label_en: "Academic Structure",
        label_ar: "الهيكل الأكاديمي",
        href_en: "/en/academics/structure",
        href_ar: "/ar/academics/structure",
        icon: Network,
      },
      {
        key: "academics-subjects",
        label_en: "Subjects & Allocation",
        label_ar: "المواد وتوزيعها",
        href_en: "/en/academics/subjects",
        href_ar: "/ar/academics/subjects",
        icon: BookOpen,
      },
      {
        key: "academics-curriculum",
        label_en: "Curriculum",
        label_ar: "المنهج",
        href_en: "/en/academics/curriculum",
        href_ar: "/ar/academics/curriculum",
        icon: FileText,
      },

      {
        key: "academics-calendar",
        label_en: "Academic Calendar",
        label_ar: "التقويم الأكاديمي",
        href_en: "/en/academics/calendar",
        href_ar: "/ar/academics/calendar",
        icon: ClipboardCheck,
      },
      {
        key: "academics-timetable",
        label_en: "Time Table",
        label_ar: "الجدول",
        href_en: "/en/academics/timetable",
        href_ar: "/ar/academics/timetable",
        icon: Clock,
      },
      {
        key: "academics-lesson-plans",
        label_en: "Lesson Plans",
        label_ar: "خطة الدروس",
        href_en: "/en/academics/lesson-plans",
        href_ar: "/ar/academics/lesson-plans",
        icon: Calendar,
      },
      {
        key: "academics-teacher-allocation",
        label_en: "Teacher Allocation",
        label_ar: "توزيع المعلمين",
        href_en: "/en/academics/teacher-allocation",
        href_ar: "/ar/academics/teacher-allocation",
        icon: UserCheck,
      },
      {
        key: "teachers",
        label_en: "Teachers Management",
        label_ar: "إدارة المعلمين",
        href_en: "/en/teachers",
        href_ar: "/ar/teachers",
        icon: Users,
      },
    ],
  },

  {
    key: "grades",
    label_en: "Assessments & Grades",
    label_ar: "التقييمات والدرجات",
    href_en: "/en/grades",
    href_ar: "/ar/grades",
    icon: ClipboardCheck,
    children: [
      {
        key: "grades-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/grades",
        href_ar: "/ar/grades",
        icon: LayoutDashboard,
      },
      {
        key: "grades-assessments",
        label_en: "Assessments",
        label_ar: "التقييمات",
        href_en: "/en/grades/assessments",
        href_ar: "/ar/grades/assessments",
        icon: ClipboardCheck,
      },
      {
        key: "grades-gradebook",
        label_en: "Gradebook",
        label_ar: "الدرجات",
        href_en: "/en/grades/gradebook",
        href_ar: "/ar/grades/gradebook",
        icon: BookOpen,
      },
    ],
  },
  {
    key: "attendance",
    label_en: "Attendance & Discipline",
    label_ar: "الحضور والانضباط",
    href_en: "/en/attendance/policies",
    href_ar: "/ar/attendance/policies",
    icon: ClipboardList,
    children: [
      {
        key: "attendance-reports",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/attendance/reports",
        href_ar: "/ar/attendance/reports",
        icon: LayoutDashboard,
      },
      {
        key: "attendance-policies",
        label_en: "Policies",
        label_ar: "السياسات",
        href_en: "/en/attendance/policies",
        href_ar: "/ar/attendance/policies",
        icon: FileText,
      },
      {
        key: "attendance-roll-call",
        label_en: "Live Roll Call",
        label_ar: "كشف الحضور المباشر",
        href_en: "/en/attendance/roll-call",
        href_ar: "/ar/attendance/roll-call",
        icon: ClipboardCheck,
      },
      {
        key: "attendance-absences",
        label_en: "Absences & Leaves",
        label_ar: "الغياب والإجازات",
        href_en: "/en/attendance/absences",
        href_ar: "/ar/attendance/absences",
        icon: UserMinus,
      },
      {
        key: "attendance-late-early",
        label_en: "Late/Early",
        label_ar: "التأخير/المغادرة المبكرة",
        href_en: "/en/attendance/late-early",
        href_ar: "/ar/attendance/late-early",
        icon: Clock,
      },
      {
        key: "attendance-excuses",
        label_en: "Excuses",
        label_ar: "الأعذار",
        href_en: "/en/attendance/excuses",
        href_ar: "/ar/attendance/excuses",
        icon: MessageSquare,
      },
    ],
  },
  {
    key: "nedaa",
    label_en: "Nedaa",
    label_ar: "نداء",
    href_en: "/en/nedaa",
    href_ar: "/ar/nedaa",
    icon: BellRing,
    children: [
      {
        key: "nedaa-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/nedaa",
        href_ar: "/ar/nedaa",
        icon: LayoutDashboard,
      },
      {
        key: "nedaa-requests",
        label_en: "Requests",
        label_ar: "الطلبات",
        href_en: "/en/nedaa/requests",
        href_ar: "/ar/nedaa/requests",
        icon: ClipboardList,
      },
      {
        key: "nedaa-gates",
        label_en: "Gates",
        label_ar: "البوابات",
        href_en: "/en/nedaa/gates",
        href_ar: "/ar/nedaa/gates",
        icon: Network,
      },
      {
        key: "nedaa-history",
        label_en: "History",
        label_ar: "السجل",
        href_en: "/en/nedaa/history",
        href_ar: "/ar/nedaa/history",
        icon: Clock,
      },
      {
        key: "nedaa-settings",
        label_en: "Settings",
        label_ar: "الإعدادات",
        href_en: "/en/nedaa/settings",
        href_ar: "/ar/nedaa/settings",
        icon: ShieldCheck,
      },
    ],
  },
  {
    key: "reinforcement",
    label_en: "Reinforcement",
    label_ar: "التعزيز",
    href_en: "/en/reinforcement",
    href_ar: "/ar/reinforcement",
    icon: Award,
    children: [
      {
        key: "reinforcement-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/reinforcement",
        href_ar: "/ar/reinforcement",
        icon: LayoutDashboard,
      },
      {
        key: "reinforcement-tasks",
        label_en: "Tasks",
        label_ar: "المهام",
        href_en: "/en/reinforcement/tasks",
        href_ar: "/ar/reinforcement/tasks",
        icon: ClipboardCheck,
      },
    ],
  },
  {
    key: "settings",
    label_en: "Settings & Integrations",
    label_ar: "الإعدادات والتكاملات",
    href_en: "/en/settings",
    href_ar: "/ar/settings",
    icon: ShieldCheck,
    children: [
      {
        key: "settings-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/settings",
        href_ar: "/ar/settings",
        icon: LayoutDashboard,
      },
      {
        key: "settings-branding",
        label_en: "Branding & Profile",
        label_ar: "الهوية وملف المدرسة",
        href_en: "/en/settings/branding",
        href_ar: "/ar/settings/branding",
        icon: Building2,
      },
      {
        key: "settings-users",
        label_en: "Users",
        label_ar: "المستخدمون",
        href_en: "/en/settings/users",
        href_ar: "/ar/settings/users",
        icon: Users,
      },
      {
        key: "settings-roles",
        label_en: "Roles & Permissions",
        label_ar: "الأدوار والصلاحيات",
        href_en: "/en/settings/roles",
        href_ar: "/ar/settings/roles",
        icon: ShieldCheck,
      },
      {
        key: "settings-policies",
        label_en: "Policies",
        label_ar: "السياسات",
        href_en: "/en/settings/policies",
        href_ar: "/ar/settings/policies",
        icon: FileText,
      },
      {
        key: "settings-admissions-documents",
        label_en: "Admissions Documents",
        label_ar: "مستندات التقديم",
        href_en: "/en/settings/admissions-documents",
        href_ar: "/ar/settings/admissions-documents",
        icon: FolderOpen,
      },
      {
        key: "settings-templates",
        label_en: "Notification Templates",
        label_ar: "قوالب الإشعارات",
        href_en: "/en/settings/templates",
        href_ar: "/ar/settings/templates",
        icon: BellRing,
      },
      {
        key: "settings-integrations",
        label_en: "Integrations",
        label_ar: "التكاملات",
        href_en: "/en/settings/integrations",
        href_ar: "/ar/settings/integrations",
        icon: PlugZap,
      },
      {
        key: "settings-security",
        label_en: "Security & Audit",
        label_ar: "الأمان وسجل المراجعة",
        href_en: "/en/settings/security",
        href_ar: "/ar/settings/security",
        icon: ShieldCheck,
      },
      {
        key: "settings-backup",
        label_en: "Backup & Migration",
        label_ar: "النسخ الاحتياطي والترحيل",
        href_en: "/en/settings/backup",
        href_ar: "/ar/settings/backup",
        icon: FolderOpen,
      },
    ],
  },
];

export const bottomItems: MenuItem[] = [
  {
    key: "help",
    label_en: "Get Help",
    label_ar: "المساعدة",
    href_en: "/en/dashboard/help",
    href_ar: "/ar/dashboard/help",
    icon: HelpCircle,
  },
];
