import {
  Home,
  Users,
  HelpCircle,
  UserPlus,
  LayoutDashboard,
  FileText,
  ClipboardCheck,
  MessageSquare,
  CheckCircle,
  GraduationCap,
  UserCheck,
  FolderOpen,
  UserMinus,
  BookOpen,
  Network,
  Clock,
  Calendar,
  ClipboardList,
  ShieldCheck,
  KeyRound,
  AtSign,
  BellRing,
  Mail,
  Send,
  Building2,
  Award,
  ListChecks,
  CheckSquare,
  Gift,
  Settings2,
  Activity,
  Route,
} from "lucide-react";
import {
  mockLeads,
  mockApplications,
  mockTests,
  mockInterviews,
  mockDecisions,
} from "@/data/mockDataLinked";

interface MenuItem {
  key: string;
  label_en: string;
  label_ar: string;
  href_en: string;
  href_ar: string;
  icon: React.ComponentType<{ className?: string }>;
  children?: MenuItem[];
  badge?: () => number; // Function to get dynamic badge count
  buttonVariant?: "default" | "highlight";
  buttonBackgroundImage?: string;
}

export const menuItems: MenuItem[] = [
  {
    key: "hero-journey",
    label_en: "Hero Journey",
    label_ar: "رحلة البطل",
    href_en: "/en/hero-journey",
    href_ar: "/ar/hero-journey",
    icon: Award,
    buttonBackgroundImage: "/images/hero_journey/hero_journey_bg.svg",
  },
  {
    key: "dashboard",
    label_en: "Dashboard",
    label_ar: "لوحة المراقبة",
    href_en: "/en/dashboard",
    href_ar: "/ar/dashboard",
    icon: Home,
  },
  {
    key: "communication",
    label_en: "Communication",
    label_ar: "التواصل",
    href_en: "/en/communication",
    href_ar: "/ar/communication",
    icon: MessageSquare,
    children: [
      {
        key: "communication-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/communication",
        href_ar: "/ar/communication",
        icon: LayoutDashboard,
      },
      {
        key: "communication-conversations",
        label_en: "Conversations",
        label_ar: "المحادثات",
        href_en: "/en/communication/conversations",
        href_ar: "/ar/communication/conversations",
        icon: MessageSquare,
      },
      {
        key: "communication-announcements",
        label_en: "Announcements",
        label_ar: "الإعلانات",
        href_en: "/en/communication/announcements",
        href_ar: "/ar/communication/announcements",
        icon: BellRing,
      },
      {
        key: "communication-notifications",
        label_en: "Notifications",
        label_ar: "الإشعارات",
        href_en: "/en/communication/notifications",
        href_ar: "/ar/communication/notifications",
        icon: BellRing,
      },
      {
        key: "communication-notification-deliveries",
        label_en: "Notification Deliveries",
        label_ar: "تسليم الإشعارات",
        href_en: "/en/communication/notification-deliveries",
        href_ar: "/ar/communication/notification-deliveries",
        icon: Send,
      },
      {
        key: "communication-safety",
        label_en: "Safety & Moderation",
        label_ar: "الأمان والإشراف",
        href_en: "/en/communication/moderation",
        href_ar: "/ar/communication/moderation",
        icon: ShieldCheck,
      },
      {
        key: "communication-settings",
        label_en: "Settings",
        label_ar: "الإعدادات",
        href_en: "/en/communication/settings",
        href_ar: "/ar/communication/settings",
        icon: ShieldCheck,
      },
    ],
  },
  {
    key: "admissions-registration",
    label_en: "Admissions & Registration",
    label_ar: "القبول والتسجيل",
    href_en: "/en/admissions/applications",
    href_ar: "/ar/admissions/applications",
    icon: UserPlus,
    children: [
      {
        key: "admissions-applications",
        label_en: "Applications",
        label_ar: "طلبات الالتحاق",
        href_en: "/en/admissions/applications",
        href_ar: "/ar/admissions/applications",
        icon: FileText,
        badge: () =>
          mockApplications.filter((app) => app.status === "submitted").length,
      },
      {
        key: "admissions-leads",
        label_en: "Leads",
        label_ar: "الاستفسارات",
        href_en: "/en/admissions/leads",
        href_ar: "/ar/admissions/leads",
        icon: Users,
        badge: () => mockLeads.filter((lead) => lead.status === "New").length,
      },
      {
        key: "admissions-tests",
        label_en: "Tests",
        label_ar: "الاختبارات",
        href_en: "/en/admissions/tests",
        href_ar: "/ar/admissions/tests",
        icon: ClipboardCheck,
        badge: () =>
          mockTests.filter((test) => test.status === "scheduled").length,
      },
      {
        key: "admissions-interviews",
        label_en: "Interviews",
        label_ar: "المقابلات",
        href_en: "/en/admissions/interviews",
        href_ar: "/ar/admissions/interviews",
        icon: MessageSquare,
        badge: () =>
          mockInterviews.filter((interview) => interview.status === "scheduled")
            .length,
      },
      {
        key: "admissions-decisions",
        label_en: "Decisions",
        label_ar: "القرارات",
        href_en: "/en/admissions/decisions",
        href_ar: "/ar/admissions/decisions",
        icon: CheckCircle,
        badge: () =>
          mockDecisions.filter((decision) => decision.decision === "waitlist")
            .length,
      },
      {
        key: "admissions-enrollment",
        label_en: "Enrollment",
        label_ar: "التسجيل",
        href_en: "/en/admissions/enrollment",
        href_ar: "/ar/admissions/enrollment",
        icon: GraduationCap,
      },
      {
        key: "admissions-workflow-policy",
        label_en: "Workflow Policy",
        label_ar: "سياسة سير العمل",
        href_en: "/en/admissions/workflow-policy",
        href_ar: "/ar/admissions/workflow-policy",
        icon: Route,
      },
    ],
  },

  {
    key: "students-guardians",
    label_en: "Students & Guardians",
    label_ar: "الطلاب وأولياء الأمور",
    href_en: "/en/students-guardians",
    href_ar: "/ar/students-guardians",
    icon: GraduationCap,
    children: [
      {
        key: "students-guardians-dashboard",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/students-guardians",
        href_ar: "/ar/students-guardians",
        icon: LayoutDashboard,
      },
      {
        key: "students-list",
        label_en: "Students",
        label_ar: "الطلاب",
        href_en: "/en/students-guardians/students",
        href_ar: "/ar/students-guardians/students",
        icon: Users,
      },
      {
        key: "guardians-list",
        label_en: "Guardians",
        label_ar: "أولياء الأمور",
        href_en: "/en/students-guardians/guardians",
        href_ar: "/ar/students-guardians/guardians",
        icon: UserCheck,
      },
      {
        key: "profile-correction-requests",
        label_en: "Profile Correction Requests",
        label_ar: "طلبات تصحيح الملف",
        href_en: "/en/students-guardians/profile-correction-requests",
        href_ar: "/ar/students-guardians/profile-correction-requests",
        icon: ClipboardCheck,
      },
      // {
      //   key: "documents-center",
      //   label_en: "Documents",
      //   label_ar: "المستندات",
      //   href_en: "/en/students-guardians/documents",
      //   href_ar: "/ar/students-guardians/documents",
      //   icon: FolderOpen,
      // },
      // {
      //   key: "transfers",
      //   label_en: "Transfers",
      //   label_ar: "التحويلات",
      //   href_en: "/en/students-guardians/transfers-withdrawals/transfers",
      //   href_ar: "/ar/students-guardians/transfers-withdrawals/transfers",
      //   icon: ArrowLeftRight,
      //   children: [
      //     {
      //       key: "transfers-overview",
      //       label_en: "Overview",
      //       label_ar: "نظرة عامة",
      //       href_en: "/en/students-guardians/transfers-withdrawals/transfers",
      //       href_ar: "/ar/students-guardians/transfers-withdrawals/transfers",
      //       icon: LayoutDashboard,
      //     },
      //     {
      //       key: "transfers-applications",
      //       label_en: "Applications",
      //       label_ar: "الطلبات",
      //       href_en:
      //         "/en/students-guardians/transfers-withdrawals/transfers/applications",
      //       href_ar:
      //         "/ar/students-guardians/transfers-withdrawals/transfers/applications",
      //       icon: FileText,
      //     },
      //   ],
      // },
      // {
      //   key: "withdrawals",
      //   label_en: "Withdrawals",
      //   label_ar: "الانسحابات",
      //   href_en: "/en/students-guardians/transfers-withdrawals/withdrawals",
      //   href_ar: "/ar/students-guardians/transfers-withdrawals/withdrawals",
      //   icon: UserMinus,
      //   children: [
      //     {
      //       key: "withdrawals-overview",
      //       label_en: "Overview",
      //       label_ar: "نظرة عامة",
      //       href_en: "/en/students-guardians/transfers-withdrawals/withdrawals",
      //       href_ar: "/ar/students-guardians/transfers-withdrawals/withdrawals",
      //       icon: LayoutDashboard,
      //     },
      //     {
      //       key: "withdrawals-applications",
      //       label_en: "Applications",
      //       label_ar: "الطلبات",
      //       href_en:
      //         "/en/students-guardians/transfers-withdrawals/withdrawals/applications",
      //       href_ar:
      //         "/ar/students-guardians/transfers-withdrawals/withdrawals/applications",
      //       icon: FileText,
      //     },
      //   ],
      // },
    ],
  },
  {
    key: "academics",
    label_en: "Academics",
    label_ar: "الأكاديميات",
    href_en: "/en/academics",
    href_ar: "/ar/academics",
    icon: BookOpen,
    children: [
      {
        key: "academics-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/academics",
        href_ar: "/ar/academics",
        icon: LayoutDashboard,
      },
      {
        key: "academics-structure",
        label_en: "Academic Structure",
        label_ar: "الهيكل الأكاديمي",
        href_en: "/en/academics/structure",
        href_ar: "/ar/academics/structure",
        icon: Network,
      },
      {
        key: "academics-rooms",
        label_en: "Rooms",
        label_ar: "الغرف",
        href_en: "/en/academics/rooms",
        href_ar: "/ar/academics/rooms",
        icon: Building2,
      },
      {
        key: "academics-subjects",
        label_en: "Subjects & Allocation",
        label_ar: "المواد وتوزيعها",
        href_en: "/en/academics/subjects",
        href_ar: "/ar/academics/subjects",
        icon: BookOpen,
      },
      {
        key: "academics-curriculum",
        label_en: "Curriculum",
        label_ar: "المنهج",
        href_en: "/en/academics/curriculum",
        href_ar: "/ar/academics/curriculum",
        icon: FileText,
      },
      {
        key: "academics-homework",
        label_en: "Homework",
        label_ar: "الواجبات",
        href_en: "/en/academics/homework",
        href_ar: "/ar/academics/homework",
        icon: ClipboardList,
      },

      {
        key: "academics-calendar",
        label_en: "Academic Calendar",
        label_ar: "التقويم الأكاديمي",
        href_en: "/en/academics/calendar",
        href_ar: "/ar/academics/calendar",
        icon: ClipboardCheck,
      },
      {
        key: "academics-timetable",
        label_en: "Time Table",
        label_ar: "الجدول",
        href_en: "/en/academics/timetable",
        href_ar: "/ar/academics/timetable",
        icon: Clock,
      },
      {
        key: "academics-lesson-plans",
        label_en: "Lesson Plans",
        label_ar: "خطة الدروس",
        href_en: "/en/academics/lesson-plans",
        href_ar: "/ar/academics/lesson-plans",
        icon: Calendar,
      },
      {
        key: "academics-teacher-allocation",
        label_en: "Teacher Allocation",
        label_ar: "توزيع المعلمين",
        href_en: "/en/academics/teacher-allocation",
        href_ar: "/ar/academics/teacher-allocation",
        icon: UserCheck,
      },
      {
        key: "teachers",
        label_en: "Teachers Management",
        label_ar: "إدارة المعلمين",
        href_en: "/en/teachers",
        href_ar: "/ar/teachers",
        icon: Users,
      },
    ],
  },

  {
    key: "grades",
    label_en: "Assessments & Grades",
    label_ar: "التقييمات والدرجات",
    href_en: "/en/grades",
    href_ar: "/ar/grades",
    icon: ClipboardCheck,
    children: [
      {
        key: "grades-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/grades",
        href_ar: "/ar/grades",
        icon: LayoutDashboard,
      },
      {
        key: "grades-assessments",
        label_en: "Assessments",
        label_ar: "التقييمات",
        href_en: "/en/grades/assessments",
        href_ar: "/ar/grades/assessments",
        icon: ClipboardCheck,
      },
      {
        key: "grades-gradebook",
        label_en: "Gradebook",
        label_ar: "الدرجات",
        href_en: "/en/grades/gradebook",
        href_ar: "/ar/grades/gradebook",
        icon: BookOpen,
      },
      {
        key: "grades-rules",
        label_en: "Grade Rules",
        label_ar: "قواعد الدرجات",
        href_en: "/en/grades/rules",
        href_ar: "/ar/grades/rules",
        icon: Settings2,
      },
    ],
  },
  {
    key: "attendance",
    label_en: "Attendance & Discipline",
    label_ar: "الحضور والانضباط",
    href_en: "/en/attendance/policies",
    href_ar: "/ar/attendance/policies",
    icon: ClipboardList,
    children: [
      {
        key: "attendance-reports",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/attendance/reports",
        href_ar: "/ar/attendance/reports",
        icon: LayoutDashboard,
      },
      {
        key: "attendance-policies",
        label_en: "Policies",
        label_ar: "السياسات",
        href_en: "/en/attendance/policies",
        href_ar: "/ar/attendance/policies",
        icon: FileText,
      },
      {
        key: "attendance-roll-call",
        label_en: "Live Roll Call",
        label_ar: "كشف الحضور المباشر",
        href_en: "/en/attendance/roll-call",
        href_ar: "/ar/attendance/roll-call",
        icon: ClipboardCheck,
      },
      {
        key: "attendance-absences",
        label_en: "Absences & Leaves",
        label_ar: "الغياب والإجازات",
        href_en: "/en/attendance/absences",
        href_ar: "/ar/attendance/absences",
        icon: UserMinus,
      },
      {
        key: "attendance-late-early",
        label_en: "Late/Early",
        label_ar: "التأخير/المغادرة المبكرة",
        href_en: "/en/attendance/late-early",
        href_ar: "/ar/attendance/late-early",
        icon: Clock,
      },

      {
        key: "attendance-excuses",
        label_en: "Excuses",
        label_ar: "الأعذار",
        href_en: "/en/attendance/excuses",
        href_ar: "/ar/attendance/excuses",
        icon: MessageSquare,
      },
    ],
  },
  {
    key: "behavior",
    label_en: "Behavior",
    label_ar: "السلوك",
    href_en: "/en/behavior/overview",
    href_ar: "/ar/behavior/overview",
    icon: ShieldCheck,
    children: [
      {
        key: "behavior-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/behavior/overview",
        href_ar: "/ar/behavior/overview",
        icon: LayoutDashboard,
      },
      {
        key: "behavior-reviews",
        label_en: "Reviews",
        label_ar: "المراجعة",
        href_en: "/en/behavior/reviews",
        href_ar: "/ar/behavior/reviews",
        icon: ClipboardCheck,
      },
      {
        key: "behavior-records",
        label_en: "Records",
        label_ar: "السجلات",
        href_en: "/en/behavior/records",
        href_ar: "/ar/behavior/records",
        icon: ListChecks,
      },
      {
        key: "behavior-categories",
        label_en: "Categories",
        label_ar: "الفئات",
        href_en: "/en/behavior/categories",
        href_ar: "/ar/behavior/categories",
        icon: FolderOpen,
      },
    ],
  },
  {
    key: "nedaa",
    label_en: "Nedaa",
    label_ar: "نداء",
    href_en: "/en/nedaa/settings",
    href_ar: "/ar/nedaa/settings",
    icon: BellRing,
    children: [
      {
        key: "nedaa-operations",
        label_en: "Operations",
        label_ar: "عمليات نداء",
        href_en: "/en/nedaa/operations",
        href_ar: "/ar/nedaa/operations",
        icon: Activity,
      },
      {
        key: "nedaa-settings",
        label_en: "Settings",
        label_ar: "الإعدادات",
        href_en: "/en/nedaa/settings",
        href_ar: "/ar/nedaa/settings",
        icon: ShieldCheck,
      },
      {
        key: "nedaa-gates",
        label_en: "Gates",
        label_ar: "البوابات",
        href_en: "/en/nedaa/gates",
        href_ar: "/ar/nedaa/gates",
        icon: Network,
      },
      {
        key: "nedaa-staff-assignments",
        label_en: "Staff Assignments",
        label_ar: "تكليفات الموظفين",
        href_en: "/en/nedaa/staff-assignments",
        href_ar: "/ar/nedaa/staff-assignments",
        icon: UserCheck,
      },
    ],
  },
  {
    key: "reinforcement",
    label_en: "Reinforcement",
    label_ar: "التعزيز",
    href_en: "/en/reinforcement",
    href_ar: "/ar/reinforcement",
    icon: Award,
    children: [
      {
        key: "reinforcement-overview",
        label_en: "Overview",
        label_ar: "النظرة العامة",
        href_en: "/en/reinforcement",
        href_ar: "/ar/reinforcement",
        icon: LayoutDashboard,
      },
      {
        key: "reinforcement-templates",
        label_en: "Templates",
        label_ar: "القوالب",
        href_en: "/en/reinforcement/templates",
        href_ar: "/ar/reinforcement/templates",
        icon: FileText,
      },
      {
        key: "reinforcement-tasks",
        label_en: "Tasks",
        label_ar: "المهام",
        href_en: "/en/reinforcement/tasks",
        href_ar: "/ar/reinforcement/tasks",
        icon: ClipboardCheck,
      },
      {
        key: "reinforcement-xp-policies",
        label_en: "XP Policies",
        label_ar: "سياسات النقاط",
        href_en: "/en/reinforcement/xp/policies",
        href_ar: "/ar/reinforcement/xp/policies",
        icon: ShieldCheck,
      },
      {
        key: "reinforcement-xp-ledger",
        label_en: "XP Ledger",
        label_ar: "سجل النقاط",
        href_en: "/en/reinforcement/xp/ledger",
        href_ar: "/ar/reinforcement/xp/ledger",
        icon: ClipboardList,
      },
      {
        key: "reinforcement-reviews",
        label_en: "Reviews",
        label_ar: "المراجعات",
        href_en: "/en/reinforcement/reviews",
        href_ar: "/ar/reinforcement/reviews",
        icon: CheckSquare,
      },
      {
        key: "reinforcement-rewards",
        label_en: "Rewards",
        label_ar: "المكافآت",
        href_en: "/en/reinforcement/rewards",
        href_ar: "/ar/reinforcement/rewards",
        icon: Gift,
      },
    ],
  },
  {
    key: "settings",
    label_en: "Settings & Integrations",
    label_ar: "الإعدادات والتكاملات",
    href_en: "/en/settings",
    href_ar: "/ar/settings",
    icon: ShieldCheck,
    children: [
      {
        key: "settings-overview",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/settings",
        href_ar: "/ar/settings",
        icon: LayoutDashboard,
      },
      {
        key: "settings-branding",
        label_en: "Branding & Profile",
        label_ar: "الهوية وملف المدرسة",
        href_en: "/en/settings/branding",
        href_ar: "/ar/settings/branding",
        icon: Building2,
      },
      {
        key: "settings-users",
        label_en: "Users",
        label_ar: "المستخدمون",
        href_en: "/en/settings/users",
        href_ar: "/ar/settings/users",
        icon: Users,
      },
      {
        key: "settings-login-identity",
        label_en: "Login Identity",
        label_ar: "هوية تسجيل الدخول",
        href_en: "/en/settings/login-identity",
        href_ar: "/ar/settings/login-identity",
        icon: AtSign,
      },
      {
        key: "settings-credentials",
        label_en: "Credentials",
        label_ar: "بيانات الدخول",
        href_en: "/en/settings/credentials",
        href_ar: "/ar/settings/credentials",
        icon: KeyRound,
      },
      {
        key: "settings-roles",
        label_en: "Roles & Permissions",
        label_ar: "الأدوار والصلاحيات",
        href_en: "/en/settings/roles",
        href_ar: "/ar/settings/roles",
        icon: ShieldCheck,
      },
      {
        key: "settings-email-connection",
        label_en: "Email Connection",
        label_ar: "اتصال البريد",
        href_en: "/en/settings/email/connection",
        href_ar: "/ar/settings/email/connection",
        icon: Mail,
      },
      {
        key: "settings-email-templates",
        label_en: "Email Templates",
        label_ar: "قوالب البريد",
        href_en: "/en/settings/email/templates",
        href_ar: "/ar/settings/email/templates",
        icon: FileText,
      },
      {
        key: "settings-email-credential-deliveries",
        label_en: "Credential Delivery",
        label_ar: "إرسال بيانات الدخول",
        href_en: "/en/settings/email/credential-deliveries",
        href_ar: "/ar/settings/email/credential-deliveries",
        icon: Send,
      },
      {
        key: "settings-email-deliveries",
        label_en: "Email Deliveries",
        label_ar: "تسليم البريد",
        href_en: "/en/settings/email/deliveries",
        href_ar: "/ar/settings/email/deliveries",
        icon: ClipboardList,
      },
      {
        key: "settings-email-campaigns",
        label_en: "Email Campaigns",
        label_ar: "حملات البريد",
        href_en: "/en/settings/email/campaigns",
        href_ar: "/ar/settings/email/campaigns",
        icon: MessageSquare,
      },
      {
        key: "settings-security",
        label_en: "Security & Audit",
        label_ar: "الأمان وسجل المراجعة",
        href_en: "/en/settings/security",
        href_ar: "/ar/settings/security",
        icon: ShieldCheck,
      },
      {
        key: "settings-backup",
        label_en: "Backup & Migration",
        label_ar: "النسخ الاحتياطي والترحيل",
        href_en: "/en/settings/backup",
        href_ar: "/ar/settings/backup",
        icon: FolderOpen,
      },
    ],
  },
];

export const bottomItems: MenuItem[] = [
  {
    key: "system-health",
    label_en: "System Health",
    label_ar: "صحة النظام",
    href_en: "/en/settings/health",
    href_ar: "/ar/settings/health",
    icon: Activity,
  },
  {
    key: "help",
    label_en: "Get Help",
    label_ar: "المساعدة",
    href_en: "/en/dashboard/help",
    href_ar: "/ar/dashboard/help",
    icon: HelpCircle,
  },
];
