import {
  Home,
  Users,
  HelpCircle,
  UserPlus,
  LayoutDashboard,
  FileText,
  ClipboardCheck,
  MessageSquare,
  CheckCircle,
  GraduationCap,
  UserCheck,
  FolderOpen,
  UserMinus,
  BookOpen,
  Network,
  Clock,
  Calendar,
  ClipboardList,
  ShieldCheck,
  KeyRound,
  AtSign,
  BellRing,
  Mail,
  Send,
  Building2,
  Award,
  ListChecks,
  CheckSquare,
  Gift,
  Settings2,
  Activity,
  Route,
  BarChart3,
  Gauge,
  PanelsTopLeft,
} from "lucide-react";

export interface SubgroupDefinition {
  key: string;
  label_en: string;
  label_ar: string;
}

interface MenuItem {
  key: string;
  label_en: string;
  label_ar: string;
  href_en: string;
  href_ar: string;
  icon: React.ComponentType<{ className?: string }>;
  children?: MenuItem[];
  subgroup?: string;
  subgroups?: SubgroupDefinition[];
  badge?: () => number; // Function to get dynamic badge count
  buttonVariant?: "default" | "highlight";
  buttonBackgroundImage?: string;
}

export interface GroupedMenuChildren {
  subgroup: SubgroupDefinition;
  children: MenuItem[];
}

const normalizeNavigationText = (value: string) =>
  value.trim().toLocaleLowerCase();

export function filterMenuItems(
  items: MenuItem[],
  query: string,
  isArabic: boolean,
): MenuItem[] {
  const normalizedQuery = normalizeNavigationText(query);
  if (!normalizedQuery) return items;

  return items.flatMap((item) => {
    const itemLabel = isArabic ? item.label_ar : item.label_en;
    const itemMatches =
      normalizeNavigationText(itemLabel).includes(normalizedQuery);

    if (!item.children) {
      return itemMatches ? [item] : [];
    }

    const matchingChildren = filterMenuItems(item.children, query, isArabic);
    if (!itemMatches && matchingChildren.length === 0) {
      return [];
    }

    return [
      {
        ...item,
        children: itemMatches ? item.children : matchingChildren,
      },
    ];
  });
}

export function groupMenuChildren(
  item: MenuItem,
  children: MenuItem[],
): GroupedMenuChildren[] {
  return (item.subgroups ?? [])
    .map((subgroup) => ({
      subgroup,
      children: children.filter((child) => child.subgroup === subgroup.key),
    }))
    .filter((group) => group.children.length > 0);
}

export const menuItems: MenuItem[] = [
  {
    key: "hero-journey",
    label_en: "Hero Journey",
    label_ar: "رحلة البطل",
    href_en: "/en/hero-journey",
    href_ar: "/ar/hero-journey",
    icon: Award,
    buttonBackgroundImage: "/images/hero_journey/hero_journey_bg.svg",
  },
  {
    key: "dashboard",
    label_en: "Dashboard",
    label_ar: "لوحة المراقبة",
    href_en: "/en/dashboard",
    href_ar: "/ar/dashboard",
    icon: Home,
    subgroups: [{ key: "general", label_en: "General", label_ar: "عام" }],
    children: [
      {
        key: "dashboard-overview",
        subgroup: "general",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/dashboard",
        href_ar: "/ar/dashboard",
        icon: LayoutDashboard,
      },
      {
        key: "dashboard-analytics",
        subgroup: "general",
        label_en: "Analytics",
        label_ar: "التحليلات",
        href_en: "/en/dashboard/analytics",
        href_ar: "/ar/dashboard/analytics",
        icon: BarChart3,
      },
      {
        key: "dashboard-command-center",
        subgroup: "general",
        label_en: "Command Center",
        label_ar: "مركز القيادة",
        href_en: "/en/dashboard/command-center",
        href_ar: "/ar/dashboard/command-center",
        icon: Gauge,
      },
      {
        key: "dashboard-widgets",
        subgroup: "general",
        label_en: "Widgets",
        label_ar: "الأدوات",
        href_en: "/en/dashboard/widgets",
        href_ar: "/ar/dashboard/widgets",
        icon: PanelsTopLeft,
      },
    ],
  },
  {
    key: "communication",
    label_en: "Communication",
    label_ar: "التواصل",
    href_en: "/en/communication",
    href_ar: "/ar/communication",
    icon: MessageSquare,
    subgroups: [
      { key: "general", label_en: "General", label_ar: "عام" },
      { key: "messaging", label_en: "Messaging", label_ar: "المراسلات" },
      {
        key: "notifications",
        label_en: "Notifications",
        label_ar: "الإشعارات",
      },
      {
        key: "safety-settings",
        label_en: "Safety & Settings",
        label_ar: "الأمان والإعدادات",
      },
    ],
    children: [
      {
        key: "communication-overview",
        subgroup: "general",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/communication",
        href_ar: "/ar/communication",
        icon: LayoutDashboard,
      },
      {
        key: "communication-conversations",
        subgroup: "messaging",
        label_en: "Conversations",
        label_ar: "المحادثات",
        href_en: "/en/communication/conversations",
        href_ar: "/ar/communication/conversations",
        icon: MessageSquare,
      },
      {
        key: "communication-announcements",
        subgroup: "messaging",
        label_en: "Announcements",
        label_ar: "الإعلانات",
        href_en: "/en/communication/announcements",
        href_ar: "/ar/communication/announcements",
        icon: BellRing,
      },
      {
        key: "communication-notifications",
        subgroup: "notifications",
        label_en: "Notifications",
        label_ar: "الإشعارات",
        href_en: "/en/communication/notifications",
        href_ar: "/ar/communication/notifications",
        icon: BellRing,
      },
      {
        key: "communication-notification-deliveries",
        subgroup: "notifications",
        label_en: "Notification Deliveries",
        label_ar: "تسليم الإشعارات",
        href_en: "/en/communication/notification-deliveries",
        href_ar: "/ar/communication/notification-deliveries",
        icon: Send,
      },
      {
        key: "communication-safety",
        subgroup: "safety-settings",
        label_en: "Safety & Moderation",
        label_ar: "الأمان والإشراف",
        href_en: "/en/communication/moderation",
        href_ar: "/ar/communication/moderation",
        icon: ShieldCheck,
      },
      {
        key: "communication-settings",
        subgroup: "safety-settings",
        label_en: "Settings",
        label_ar: "الإعدادات",
        href_en: "/en/communication/settings",
        href_ar: "/ar/communication/settings",
        icon: ShieldCheck,
      },
    ],
  },
  {
    key: "admissions-registration",
    label_en: "Admissions & Registration",
    label_ar: "القبول والتسجيل",
    href_en: "/en/admissions/applications",
    href_ar: "/ar/admissions/applications",
    icon: UserPlus,
    subgroups: [
      {
        key: "pipeline",
        label_en: "Application Pipeline",
        label_ar: "مسار التقديم",
      },
      { key: "enrollment", label_en: "Enrollment", label_ar: "التسجيل" },
    ],
    children: [
      {
        key: "admissions-applications",
        subgroup: "pipeline",
        label_en: "Applications",
        label_ar: "طلبات الالتحاق",
        href_en: "/en/admissions/applications",
        href_ar: "/ar/admissions/applications",
        icon: FileText,
      },
      {
        key: "admissions-leads",
        subgroup: "pipeline",
        label_en: "Leads",
        label_ar: "الاستفسارات",
        href_en: "/en/admissions/leads",
        href_ar: "/ar/admissions/leads",
        icon: Users,
      },
      {
        key: "admissions-tests",
        subgroup: "pipeline",
        label_en: "Tests",
        label_ar: "الاختبارات",
        href_en: "/en/admissions/tests",
        href_ar: "/ar/admissions/tests",
        icon: ClipboardCheck,
      },
      {
        key: "admissions-interviews",
        subgroup: "pipeline",
        label_en: "Interviews",
        label_ar: "المقابلات",
        href_en: "/en/admissions/interviews",
        href_ar: "/ar/admissions/interviews",
        icon: MessageSquare,
      },
      {
        key: "admissions-decisions",
        subgroup: "pipeline",
        label_en: "Decisions",
        label_ar: "القرارات",
        href_en: "/en/admissions/decisions",
        href_ar: "/ar/admissions/decisions",
        icon: CheckCircle,
      },
      {
        key: "admissions-enrollment",
        subgroup: "enrollment",
        label_en: "Enrollment",
        label_ar: "التسجيل",
        href_en: "/en/admissions/enrollment",
        href_ar: "/ar/admissions/enrollment",
        icon: GraduationCap,
      },
      {
        key: "admissions-workflow-policy",
        subgroup: "enrollment",
        label_en: "Workflow Policy",
        label_ar: "سياسة سير العمل",
        href_en: "/en/admissions/workflow-policy",
        href_ar: "/ar/admissions/workflow-policy",
        icon: Route,
      },
    ],
  },

  {
    key: "students-guardians",
    subgroups: [
      { key: "directory", label_en: "Directory", label_ar: "الدليل" },
      { key: "requests", label_en: "Requests", label_ar: "الطلبات" },
    ],
    label_en: "Students & Guardians",
    label_ar: "الطلاب وأولياء الأمور",
    href_en: "/en/students-guardians",
    href_ar: "/ar/students-guardians",
    icon: GraduationCap,
    children: [
      // {
      //   key: "students-guardians-dashboard",
      //   subgroup: "directory",
      //   label_en: "Overview",
      //   label_ar: "نظرة عامة",
      //   href_en: "/en/students-guardians",
      //   href_ar: "/ar/students-guardians",
      //   icon: LayoutDashboard,
      // },
      {
        key: "students-list",
        subgroup: "directory",
        label_en: "Students",
        label_ar: "الطلاب",
        href_en: "/en/students-guardians/students",
        href_ar: "/ar/students-guardians/students",
        icon: Users,
      },
      {
        key: "guardians-list",
        subgroup: "directory",
        label_en: "Guardians",
        label_ar: "أولياء الأمور",
        href_en: "/en/students-guardians/guardians",
        href_ar: "/ar/students-guardians/guardians",
        icon: UserCheck,
      },
      {
        key: "profile-correction-requests",
        subgroup: "requests",
        label_en: "Profile Correction Requests",
        label_ar: "طلبات تصحيح الملف",
        href_en: "/en/students-guardians/profile-correction-requests",
        href_ar: "/ar/students-guardians/profile-correction-requests",
        icon: ClipboardCheck,
      },
      // {
      //   key: "documents-center",
      //   label_en: "Documents",
      //   label_ar: "المستندات",
      //   href_en: "/en/students-guardians/documents",
      //   href_ar: "/ar/students-guardians/documents",
      //   icon: FolderOpen,
      // },
      // {
      //   key: "transfers",
      //   label_en: "Transfers",
      //   label_ar: "التحويلات",
      //   href_en: "/en/students-guardians/transfers-withdrawals/transfers",
      //   href_ar: "/ar/students-guardians/transfers-withdrawals/transfers",
      //   icon: ArrowLeftRight,
      //   children: [
      //     {
      //       key: "transfers-overview",
      //       label_en: "Overview",
      //       label_ar: "نظرة عامة",
      //       href_en: "/en/students-guardians/transfers-withdrawals/transfers",
      //       href_ar: "/ar/students-guardians/transfers-withdrawals/transfers",
      //       icon: LayoutDashboard,
      //     },
      //     {
      //       key: "transfers-applications",
      //       label_en: "Applications",
      //       label_ar: "الطلبات",
      //       href_en:
      //         "/en/students-guardians/transfers-withdrawals/transfers/applications",
      //       href_ar:
      //         "/ar/students-guardians/transfers-withdrawals/transfers/applications",
      //       icon: FileText,
      //     },
      //   ],
      // },
      // {
      //   key: "withdrawals",
      //   label_en: "Withdrawals",
      //   label_ar: "الانسحابات",
      //   href_en: "/en/students-guardians/transfers-withdrawals/withdrawals",
      //   href_ar: "/ar/students-guardians/transfers-withdrawals/withdrawals",
      //   icon: UserMinus,
      //   children: [
      //     {
      //       key: "withdrawals-overview",
      //       label_en: "Overview",
      //       label_ar: "نظرة عامة",
      //       href_en: "/en/students-guardians/transfers-withdrawals/withdrawals",
      //       href_ar: "/ar/students-guardians/transfers-withdrawals/withdrawals",
      //       icon: LayoutDashboard,
      //     },
      //     {
      //       key: "withdrawals-applications",
      //       label_en: "Applications",
      //       label_ar: "الطلبات",
      //       href_en:
      //         "/en/students-guardians/transfers-withdrawals/withdrawals/applications",
      //       href_ar:
      //         "/ar/students-guardians/transfers-withdrawals/withdrawals/applications",
      //       icon: FileText,
      //     },
      //   ],
      // },
    ],
  },
  {
    key: "academics",
    subgroups: [
      {
        key: "setup",
        label_en: "Academic Setup",
        label_ar: "الإعداد الأكاديمي",
      },
      {
        key: "teaching-learning",
        label_en: "Teaching & Learning",
        label_ar: "التعليم والتعلم",
      },
      { key: "staff", label_en: "Staff", label_ar: "الموظفون" },
    ],
    label_en: "Academics",
    label_ar: "الأكاديميات",
    href_en: "/en/academics",
    href_ar: "/ar/academics",
    icon: BookOpen,
    children: [
      {
        key: "academics-overview",
        subgroup: "setup",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/academics",
        href_ar: "/ar/academics",
        icon: LayoutDashboard,
      },
      {
        key: "academics-structure",
        subgroup: "setup",
        label_en: "Academic Structure",
        label_ar: "الهيكل الأكاديمي",
        href_en: "/en/academics/structure",
        href_ar: "/ar/academics/structure",
        icon: Network,
      },
      {
        key: "academics-rooms",
        subgroup: "setup",
        label_en: "Rooms",
        label_ar: "الغرف",
        href_en: "/en/academics/rooms",
        href_ar: "/ar/academics/rooms",
        icon: Building2,
      },
      {
        key: "academics-subjects",
        subgroup: "setup",
        label_en: "Subjects & Allocation",
        label_ar: "المواد وتوزيعها",
        href_en: "/en/academics/subjects",
        href_ar: "/ar/academics/subjects",
        icon: BookOpen,
      },
      {
        key: "academics-curriculum",
        subgroup: "teaching-learning",
        label_en: "Curriculum",
        label_ar: "المنهج",
        href_en: "/en/academics/curriculum",
        href_ar: "/ar/academics/curriculum",
        icon: FileText,
      },
      {
        key: "academics-homework",
        subgroup: "teaching-learning",
        label_en: "Homework",
        label_ar: "الواجبات",
        href_en: "/en/academics/homework",
        href_ar: "/ar/academics/homework",
        icon: ClipboardList,
      },

      {
        key: "academics-calendar",
        subgroup: "teaching-learning",
        label_en: "Academic Calendar",
        label_ar: "التقويم الأكاديمي",
        href_en: "/en/academics/calendar",
        href_ar: "/ar/academics/calendar",
        icon: ClipboardCheck,
      },
      {
        key: "academics-timetable",
        subgroup: "teaching-learning",
        label_en: "Time Table",
        label_ar: "الجدول",
        href_en: "/en/academics/timetable",
        href_ar: "/ar/academics/timetable",
        icon: Clock,
      },
      {
        key: "academics-lesson-plans",
        subgroup: "teaching-learning",
        label_en: "Lesson Plans",
        label_ar: "خطة الدروس",
        href_en: "/en/academics/lesson-plans",
        href_ar: "/ar/academics/lesson-plans",
        icon: Calendar,
      },
      {
        key: "academics-teacher-allocation",
        subgroup: "staff",
        label_en: "Teacher Allocation",
        label_ar: "توزيع المعلمين",
        href_en: "/en/academics/teacher-allocation",
        href_ar: "/ar/academics/teacher-allocation",
        icon: UserCheck,
      },
      {
        key: "teachers",
        subgroup: "staff",
        label_en: "Teachers Management",
        label_ar: "إدارة المعلمين",
        href_en: "/en/teachers",
        href_ar: "/ar/teachers",
        icon: Users,
      },
    ],
  },

  {
    key: "grades",
    subgroups: [
      { key: "general", label_en: "General", label_ar: "عام" },
      {
        key: "assessment-management",
        label_en: "Assessment Management",
        label_ar: "إدارة التقييمات",
      },
    ],
    label_en: "Assessments & Grades",
    label_ar: "التقييمات والدرجات",
    href_en: "/en/grades",
    href_ar: "/ar/grades",
    icon: ClipboardCheck,
    children: [
      {
        key: "grades-overview",
        subgroup: "general",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/grades",
        href_ar: "/ar/grades",
        icon: LayoutDashboard,
      },
      {
        key: "grades-assessments",
        subgroup: "assessment-management",
        label_en: "Assessments",
        label_ar: "التقييمات",
        href_en: "/en/grades/assessments",
        href_ar: "/ar/grades/assessments",
        icon: ClipboardCheck,
      },
      {
        key: "grades-gradebook",
        subgroup: "assessment-management",
        label_en: "Gradebook",
        label_ar: "الدرجات",
        href_en: "/en/grades/gradebook",
        href_ar: "/ar/grades/gradebook",
        icon: BookOpen,
      },
      {
        key: "grades-rules",
        subgroup: "assessment-management",
        label_en: "Grade Rules",
        label_ar: "قواعد الدرجات",
        href_en: "/en/grades/rules",
        href_ar: "/ar/grades/rules",
        icon: Settings2,
      },
    ],
  },
  {
    key: "attendance",
    subgroups: [
      { key: "monitoring", label_en: "Monitoring", label_ar: "المتابعة" },
      {
        key: "policies-records",
        label_en: "Policies & Records",
        label_ar: "السياسات والسجلات",
      },
    ],
    label_en: "Attendance & Discipline",
    label_ar: "الحضور والانضباط",
    href_en: "/en/attendance/policies",
    href_ar: "/ar/attendance/policies",
    icon: ClipboardList,
    children: [
      {
        key: "attendance-reports",
        subgroup: "monitoring",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/attendance/reports",
        href_ar: "/ar/attendance/reports",
        icon: LayoutDashboard,
      },
      {
        key: "attendance-policies",
        subgroup: "policies-records",
        label_en: "Policies",
        label_ar: "السياسات",
        href_en: "/en/attendance/policies",
        href_ar: "/ar/attendance/policies",
        icon: FileText,
      },
      {
        key: "attendance-roll-call",
        subgroup: "monitoring",
        label_en: "Live Roll Call",
        label_ar: "كشف الحضور المباشر",
        href_en: "/en/attendance/roll-call",
        href_ar: "/ar/attendance/roll-call",
        icon: ClipboardCheck,
      },
      {
        key: "attendance-absences",
        subgroup: "policies-records",
        label_en: "Absences & Leaves",
        label_ar: "الغياب والإجازات",
        href_en: "/en/attendance/absences",
        href_ar: "/ar/attendance/absences",
        icon: UserMinus,
      },
      {
        key: "attendance-late-early",
        subgroup: "policies-records",
        label_en: "Late/Early",
        label_ar: "التأخير/المغادرة المبكرة",
        href_en: "/en/attendance/late-early",
        href_ar: "/ar/attendance/late-early",
        icon: Clock,
      },

      {
        key: "attendance-excuses",
        subgroup: "policies-records",
        label_en: "Excuses",
        label_ar: "الأعذار",
        href_en: "/en/attendance/excuses",
        href_ar: "/ar/attendance/excuses",
        icon: MessageSquare,
      },
    ],
  },
  {
    key: "behavior",
    subgroups: [
      { key: "general", label_en: "General", label_ar: "عام" },
      {
        key: "management",
        label_en: "Behavior Management",
        label_ar: "إدارة السلوك",
      },
    ],
    label_en: "Behavior",
    label_ar: "السلوك",
    href_en: "/en/behavior/overview",
    href_ar: "/ar/behavior/overview",
    icon: ShieldCheck,
    children: [
      {
        key: "behavior-overview",
        subgroup: "general",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/behavior/overview",
        href_ar: "/ar/behavior/overview",
        icon: LayoutDashboard,
      },
      {
        key: "behavior-reviews",
        subgroup: "management",
        label_en: "Reviews",
        label_ar: "المراجعة",
        href_en: "/en/behavior/reviews",
        href_ar: "/ar/behavior/reviews",
        icon: ClipboardCheck,
      },
      {
        key: "behavior-records",
        subgroup: "management",
        label_en: "Records",
        label_ar: "السجلات",
        href_en: "/en/behavior/records",
        href_ar: "/ar/behavior/records",
        icon: ListChecks,
      },
      {
        key: "behavior-categories",
        subgroup: "management",
        label_en: "Categories",
        label_ar: "الفئات",
        href_en: "/en/behavior/categories",
        href_ar: "/ar/behavior/categories",
        icon: FolderOpen,
      },
    ],
  },
  {
    key: "nedaa",
    subgroups: [
      { key: "operations", label_en: "Operations", label_ar: "العمليات" },
      {
        key: "configuration",
        label_en: "Configuration",
        label_ar: "الإعدادات",
      },
    ],
    label_en: "Nedaa",
    label_ar: "نداء",
    href_en: "/en/nedaa/settings",
    href_ar: "/ar/nedaa/settings",
    icon: BellRing,
    children: [
      {
        key: "nedaa-operations",
        subgroup: "operations",
        label_en: "Operations",
        label_ar: "عمليات نداء",
        href_en: "/en/nedaa/operations",
        href_ar: "/ar/nedaa/operations",
        icon: Activity,
      },
      {
        key: "nedaa-settings",
        subgroup: "configuration",
        label_en: "Settings",
        label_ar: "الإعدادات",
        href_en: "/en/nedaa/settings",
        href_ar: "/ar/nedaa/settings",
        icon: ShieldCheck,
      },
      {
        key: "nedaa-gates",
        subgroup: "operations",
        label_en: "Gates",
        label_ar: "البوابات",
        href_en: "/en/nedaa/gates",
        href_ar: "/ar/nedaa/gates",
        icon: Network,
      },
      {
        key: "nedaa-staff-assignments",
        subgroup: "operations",
        label_en: "Staff Assignments",
        label_ar: "تكليفات الموظفين",
        href_en: "/en/nedaa/staff-assignments",
        href_ar: "/ar/nedaa/staff-assignments",
        icon: UserCheck,
      },
    ],
  },
  {
    key: "reinforcement",
    subgroups: [
      { key: "general", label_en: "General", label_ar: "عام" },
      { key: "programs", label_en: "Programs", label_ar: "البرامج" },
      {
        key: "xp-rewards",
        label_en: "XP & Rewards",
        label_ar: "نقاط الخبرة والمكافآت",
      },
    ],
    label_en: "Reinforcement",
    label_ar: "التعزيز",
    href_en: "/en/reinforcement",
    href_ar: "/ar/reinforcement",
    icon: Award,
    children: [
      {
        key: "reinforcement-overview",
        subgroup: "general",
        label_en: "Overview",
        label_ar: "النظرة العامة",
        href_en: "/en/reinforcement",
        href_ar: "/ar/reinforcement",
        icon: LayoutDashboard,
      },
      {
        key: "reinforcement-templates",
        subgroup: "programs",
        label_en: "Templates",
        label_ar: "القوالب",
        href_en: "/en/reinforcement/templates",
        href_ar: "/ar/reinforcement/templates",
        icon: FileText,
      },
      {
        key: "reinforcement-tasks",
        subgroup: "programs",
        label_en: "Tasks",
        label_ar: "المهام",
        href_en: "/en/reinforcement/tasks",
        href_ar: "/ar/reinforcement/tasks",
        icon: ClipboardCheck,
      },
      {
        key: "reinforcement-xp-policies",
        subgroup: "xp-rewards",
        label_en: "XP Policies",
        label_ar: "سياسات النقاط",
        href_en: "/en/reinforcement/xp/policies",
        href_ar: "/ar/reinforcement/xp/policies",
        icon: ShieldCheck,
      },
      {
        key: "reinforcement-xp-ledger",
        subgroup: "xp-rewards",
        label_en: "XP Ledger",
        label_ar: "سجل النقاط",
        href_en: "/en/reinforcement/xp/ledger",
        href_ar: "/ar/reinforcement/xp/ledger",
        icon: ClipboardList,
      },
      {
        key: "reinforcement-reviews",
        subgroup: "xp-rewards",
        label_en: "Reviews",
        label_ar: "المراجعات",
        href_en: "/en/reinforcement/reviews",
        href_ar: "/ar/reinforcement/reviews",
        icon: CheckSquare,
      },
      {
        key: "reinforcement-rewards",
        subgroup: "xp-rewards",
        label_en: "Rewards",
        label_ar: "المكافآت",
        href_en: "/en/reinforcement/rewards",
        href_ar: "/ar/reinforcement/rewards",
        icon: Gift,
      },
    ],
  },
  {
    key: "settings",
    subgroups: [
      { key: "general", label_en: "General", label_ar: "عام" },
      {
        key: "access-identity",
        label_en: "Access & Identity",
        label_ar: "الوصول والهوية",
      },
      { key: "email", label_en: "Email", label_ar: "البريد الإلكتروني" },
      {
        key: "security-data",
        label_en: "Security & Data",
        label_ar: "الأمان والبيانات",
      },
    ],
    label_en: "Settings & Integrations",
    label_ar: "الإعدادات والتكاملات",
    href_en: "/en/settings",
    href_ar: "/ar/settings",
    icon: ShieldCheck,
    children: [
      {
        key: "settings-overview",
        subgroup: "general",
        label_en: "Overview",
        label_ar: "نظرة عامة",
        href_en: "/en/settings",
        href_ar: "/ar/settings",
        icon: LayoutDashboard,
      },
      {
        key: "dashboard-recent-activities",
        subgroup: "general",
        label_en: "Recent Activities",
        label_ar: "الأنشطة الأخيرة",
        href_en: "/en/dashboard/recent-activities",
        href_ar: "/ar/dashboard/recent-activities",
        icon: Activity,
      },
      {
        key: "settings-branding",
        subgroup: "general",
        label_en: "Branding & Profile",
        label_ar: "الهوية وملف المدرسة",
        href_en: "/en/settings/branding",
        href_ar: "/ar/settings/branding",
        icon: Building2,
      },
      {
        key: "settings-users",
        subgroup: "access-identity",
        label_en: "Users",
        label_ar: "المستخدمون",
        href_en: "/en/settings/users",
        href_ar: "/ar/settings/users",
        icon: Users,
      },
      {
        key: "settings-login-identity",
        subgroup: "access-identity",
        label_en: "Login Identity",
        label_ar: "هوية تسجيل الدخول",
        href_en: "/en/settings/login-identity",
        href_ar: "/ar/settings/login-identity",
        icon: AtSign,
      },
      {
        key: "settings-credentials",
        subgroup: "access-identity",
        label_en: "Credentials",
        label_ar: "بيانات الدخول",
        href_en: "/en/settings/credentials",
        href_ar: "/ar/settings/credentials",
        icon: KeyRound,
      },
      {
        key: "settings-roles",
        subgroup: "access-identity",
        label_en: "Roles & Permissions",
        label_ar: "الأدوار والصلاحيات",
        href_en: "/en/settings/roles",
        href_ar: "/ar/settings/roles",
        icon: ShieldCheck,
      },
      {
        key: "settings-email-connection",
        subgroup: "email",
        label_en: "Email Connection",
        label_ar: "اتصال البريد",
        href_en: "/en/settings/email/connection",
        href_ar: "/ar/settings/email/connection",
        icon: Mail,
      },
      {
        key: "settings-email-templates",
        subgroup: "email",
        label_en: "Email Templates",
        label_ar: "قوالب البريد",
        href_en: "/en/settings/email/templates",
        href_ar: "/ar/settings/email/templates",
        icon: FileText,
      },
      {
        key: "settings-email-credential-deliveries",
        subgroup: "email",
        label_en: "Credential Delivery",
        label_ar: "إرسال بيانات الدخول",
        href_en: "/en/settings/email/credential-deliveries",
        href_ar: "/ar/settings/email/credential-deliveries",
        icon: Send,
      },
      {
        key: "settings-email-deliveries",
        subgroup: "email",
        label_en: "Email Deliveries",
        label_ar: "تسليم البريد",
        href_en: "/en/settings/email/deliveries",
        href_ar: "/ar/settings/email/deliveries",
        icon: ClipboardList,
      },
      {
        key: "settings-email-campaigns",
        subgroup: "email",
        label_en: "Email Campaigns",
        label_ar: "حملات البريد",
        href_en: "/en/settings/email/campaigns",
        href_ar: "/ar/settings/email/campaigns",
        icon: MessageSquare,
      },
      {
        key: "settings-security",
        subgroup: "security-data",
        label_en: "Security & Audit",
        label_ar: "الأمان وسجل المراجعة",
        href_en: "/en/settings/security",
        href_ar: "/ar/settings/security",
        icon: ShieldCheck,
      },
      {
        key: "settings-backup",
        subgroup: "security-data",
        label_en: "Backup & Migration",
        label_ar: "النسخ الاحتياطي والترحيل",
        href_en: "/en/settings/backup",
        href_ar: "/ar/settings/backup",
        icon: FolderOpen,
      },
    ],
  },
];

export const bottomItems: MenuItem[] = [
  {
    key: "system-health",
    label_en: "System Health",
    label_ar: "صحة النظام",
    href_en: "/en/settings/health",
    href_ar: "/ar/settings/health",
    icon: Activity,
  },
  {
    key: "help",
    label_en: "Get Help",
    label_ar: "المساعدة",
    href_en: "/en/help",
    href_ar: "/ar/help",
    icon: HelpCircle,
  },
];
