export type ConversationRedesignLocale = "en" | "ar";

export const conversationRedesignLabels = {
  en: {
    conversations: "Conversations",
    manageSchoolCommunication: "Manage school communication",
    searchConversations: "Search conversations...",
    all: "All",
    unread: "Unread",
    pinned: "Pinned",
    archived: "Archived",
    closed: "Closed",
    loadingConversations: "Loading conversations...",
    noConversationsFound: "No conversations found.",
    selectConversation: "Select a conversation to start.",
    messages: "Messages",
    participants: "Participants",
    invites: "Invites",
    joinRequests: "Join Requests",
    createConversation: "Create Conversation",
    editConversation: "Edit Conversation",
    addParticipant: "Add Participant",
    createInvite: "Create Invite",
    createJoinRequest: "Create Join Request",
    reviewJoinRequest: "Review Join Request",
    rejectJoinRequest: "Reject Join Request",
    messageSent: "Message sent.",
    unableToSendMessage: "Unable to send message.",
    participantAdded: "Participant added.",
    inviteCreated: "Invite created.",
    joinRequestApproved: "Join request approved.",
    joinRequestRejected: "Join request rejected.",
    readOnly: "Read only",
    readOnlyConversation: "This conversation is read-only.",
    readOnlyComposer: "This conversation is read-only. Only admins can send messages.",
    loadingMessages: "Loading messages...",
    noMessagesYet: "No messages yet.",
    startConversation: "Start the conversation.",
    typing: "is typing...",
    send: "Send",
    cancel: "Cancel",
    save: "Save",
    create: "Create",
    refreshConversations: "Refresh conversations",
    refreshConversation: "Refresh conversation",
    backToConversations: "Back to conversations",
    searchMessages: "Search messages",
    messageSearchUnavailable: "Message search is not available yet.",
    today: "Today",
    loading: "Loading...",
    untitledConversation: "Untitled conversation",
    direct: "Direct",
    participantsCount: "Participants",
    writeMessage: "Write a message...",
    attachFile: "Attach file",
    attachFileToMessage: "Attach file to message",
    emoji: "Emoji",
    sending: "Sending",
    failed: "Failed",
    edited: "Edited",
    sent: "Sent",
    readBy: "Read by {count}",
    deleteMessageConfirm: "Delete this message?",
    deleteAttachmentConfirm: "Delete this attachment?",
    deleteMessage: "Delete",
    editMessage: "Edit",
    attachmentDeleted: "Attachment deleted.",
    unableToDeleteAttachment: "Unable to delete attachment.",
    messageDeleted: "Message deleted.",
    unableToDeleteMessage: "Unable to delete message.",
    messageUpdated: "Message updated.",
    unableToUpdateMessage: "Unable to update message.",
    reactionAdded: "Reaction added.",
    unableToAddReaction: "Unable to add reaction.",
    reactionRemoved: "Reaction removed.",
    unableToRemoveReaction: "Unable to remove reaction.",
    attachmentUploaded: "Attachment uploaded.",
    unableToUploadAttachment: "Unable to upload attachment.",
    sendMessageBeforeAttach: "Send a message first, then attach the file to it.",
    uploadingAttachment: "Uploading attachment...",
    like: "Like",
    noMessagesYetFull: "No messages yet. Start the conversation.",
    participantUpdated: "Participant updated.",
    participantPromoted: "Participant promoted.",
    participantDemoted: "Participant demoted.",
    participantRemoved: "Participant removed.",
    conversationLeft: "Conversation left.",
    inviteAccepted: "Invite accepted.",
    inviteRejected: "Invite rejected.",
    joinRequestCreated: "Join request created.",
  },
  ar: {
    conversations: "المحادثات",
    manageSchoolCommunication: "إدارة تواصل المدرسة",
    searchConversations: "ابحث في المحادثات...",
    all: "الكل",
    unread: "غير مقروءة",
    pinned: "مثبتة",
    archived: "مؤرشفة",
    closed: "مغلقة",
    loadingConversations: "جار تحميل المحادثات...",
    noConversationsFound: "لا توجد محادثات.",
    selectConversation: "اختر محادثة للبدء.",
    messages: "الرسائل",
    participants: "المشاركون",
    invites: "الدعوات",
    joinRequests: "طلبات الانضمام",
    createConversation: "إنشاء محادثة",
    editConversation: "تعديل المحادثة",
    addParticipant: "إضافة مشارك",
    createInvite: "إنشاء دعوة",
    createJoinRequest: "إنشاء طلب انضمام",
    reviewJoinRequest: "مراجعة طلب الانضمام",
    rejectJoinRequest: "رفض طلب الانضمام",
    messageSent: "تم إرسال الرسالة.",
    unableToSendMessage: "تعذر إرسال الرسالة.",
    participantAdded: "تمت إضافة المشارك.",
    inviteCreated: "تم إنشاء الدعوة.",
    joinRequestApproved: "تم قبول طلب الانضمام.",
    joinRequestRejected: "تم رفض طلب الانضمام.",
    readOnly: "للقراءة فقط",
    readOnlyConversation: "هذه المحادثة للقراءة فقط.",
    readOnlyComposer: "هذه المحادثة للقراءة فقط. يمكن للمشرفين فقط إرسال الرسائل.",
    loadingMessages: "جار تحميل الرسائل...",
    noMessagesYet: "لا توجد رسائل بعد.",
    startConversation: "ابدأ المحادثة.",
    typing: "يكتب...",
    send: "إرسال",
    cancel: "إلغاء",
    save: "حفظ",
    create: "إنشاء",
    refreshConversations: "تحديث المحادثات",
    refreshConversation: "تحديث المحادثة",
    backToConversations: "العودة إلى المحادثات",
    searchMessages: "البحث في الرسائل",
    messageSearchUnavailable: "البحث في الرسائل غير متاح حالياً.",
    today: "اليوم",
    loading: "جار التحميل...",
    untitledConversation: "محادثة بدون عنوان",
    direct: "مباشر",
    participantsCount: "مشارك",
    writeMessage: "اكتب رسالة...",
    attachFile: "إرفاق ملف",
    attachFileToMessage: "إرفاق ملف بالرسالة",
    emoji: "رمز تعبيري",
    sending: "جار الإرسال",
    failed: "فشل",
    edited: "تم التعديل",
    sent: "تم الإرسال",
    readBy: "قرأها {count}",
    deleteMessageConfirm: "حذف هذه الرسالة؟",
    deleteAttachmentConfirm: "حذف هذا المرفق؟",
    deleteMessage: "حذف",
    editMessage: "تعديل",
    attachmentDeleted: "تم حذف المرفق.",
    unableToDeleteAttachment: "تعذر حذف المرفق.",
    messageDeleted: "تم حذف الرسالة.",
    unableToDeleteMessage: "تعذر حذف الرسالة.",
    messageUpdated: "تم تحديث الرسالة.",
    unableToUpdateMessage: "تعذر تحديث الرسالة.",
    reactionAdded: "تمت إضافة التفاعل.",
    unableToAddReaction: "تعذر إضافة التفاعل.",
    reactionRemoved: "تم حذف التفاعل.",
    unableToRemoveReaction: "تعذر حذف التفاعل.",
    attachmentUploaded: "تم رفع المرفق.",
    unableToUploadAttachment: "تعذر رفع المرفق.",
    sendMessageBeforeAttach: "أرسل رسالة أولاً، ثم أرفق الملف بها.",
    uploadingAttachment: "جار رفع المرفق...",
    like: "إعجاب",
    noMessagesYetFull: "لا توجد رسائل بعد. ابدأ المحادثة.",
    participantUpdated: "تم تحديث المشارك.",
    participantPromoted: "تمت ترقية المشارك.",
    participantDemoted: "تم تخفيض دور المشارك.",
    participantRemoved: "تم حذف المشارك.",
    conversationLeft: "تمت مغادرة المحادثة.",
    inviteAccepted: "تم قبول الدعوة.",
    inviteRejected: "تم رفض الدعوة.",
    joinRequestCreated: "تم إنشاء طلب الانضمام.",
  },
} as const;

export type ConversationRedesignLabels =
  (typeof conversationRedesignLabels)[ConversationRedesignLocale];

export function labelsForLocale(locale: string): ConversationRedesignLabels {
  return locale === "ar" ? conversationRedesignLabels.ar : conversationRedesignLabels.en;
}
