export type ConversationRedesignLocale = "en" | "ar";

export const conversationRedesignLabels = {
  en: {
    conversations: "Conversations",
    manageSchoolCommunication: "Manage school communication",
    searchConversations: "Search conversations...",
    all: "All",
    mine: "Mine",
    allTypes: "All types",
    unread: "Unread",
    pinned: "Pinned",
    archived: "Archived",
    closed: "Closed",
    loadingConversations: "Loading conversations...",
    noConversationsFound: "No conversations found.",
    selectConversation: "Select a conversation to start.",
    messages: "Messages",
    participants: "Participants",
    invites: "Invites",
    joinRequests: "Join Requests",
    createConversation: "Create Conversation",
    editConversation: "Edit Conversation",
    addParticipant: "Add Participant",
    createInvite: "Create Invite",
    createJoinRequest: "Create Join Request",
    reviewJoinRequest: "Review Join Request",
    rejectJoinRequest: "Reject Join Request",
    messageSent: "Message sent.",
    unableToCreateConversation: "Unable to create conversation.",
    unableToSendMessage: "Unable to send message.",
    participantAdded: "Participant added.",
    unableToAddParticipant: "Unable to add participant.",
    unableToUpdateParticipant: "Unable to update participant.",
    unableToPromoteParticipant: "Unable to promote participant.",
    unableToDemoteParticipant: "Unable to demote participant.",
    unableToRemoveParticipant: "Unable to remove participant.",
    unableToLeaveConversation: "Unable to leave conversation.",
    inviteCreated: "Invite created.",
    unableToCreateInvite: "Unable to create invite.",
    unableToAcceptInvite: "Unable to accept invite.",
    unableToRejectInvite: "Unable to reject invite.",
    joinRequestApproved: "Join request approved.",
    unableToApproveJoinRequest: "Unable to approve join request.",
    joinRequestRejected: "Join request rejected.",
    unableToRejectJoinRequest: "Unable to reject join request.",
    unableToCreateJoinRequest: "Unable to create join request.",
    readOnly: "Read only",
    readOnlyConversation: "This conversation is read-only.",
    readOnlyComposer: "This conversation is read-only. Only admins can send messages.",
    loadingMessages: "Loading messages...",
    noMessagesYet: "No messages yet.",
    startConversation: "Start the conversation.",
    typing: "is typing...",
    send: "Send",
    cancel: "Cancel",
    dismiss: "Dismiss",
    save: "Save",
    create: "Create",
    refreshConversations: "Refresh conversations",
    refreshConversation: "Refresh conversation",
    backToConversations: "Back to conversations",
    searchMessages: "Search messages",
    messageSearchUnavailable: "Message search is not available yet.",
    today: "Today",
    yesterday: "Yesterday",
    loading: "Loading...",
    untitledConversation: "Untitled conversation",
    direct: "Direct",
    participantsCount: "Participants",
    writeMessage: "Write a message...",
    addCaption: "Add a caption...",
    voiceNote: "Voice note",
    recording: "Recording...",
    tapToRecord: "Tap to record",
    attachFile: "Attach file",
    attachFileToMessage: "Attach file to message",
    attachment: "Attachment",
    emoji: "Emoji",
    sending: "Sending",
    failed: "Failed",
    edited: "Edited",
    sent: "Sent",
    readBy: "Read by {count}",
    deleteMessageConfirm: "Delete this message?",
    deleteAttachmentConfirm: "Delete this attachment?",
    deleteMessage: "Delete",
    editMessage: "Edit",
    attachmentDeleted: "Attachment deleted.",
    unableToDeleteAttachment: "Unable to delete attachment.",
    messageDeleted: "Message deleted.",
    unableToDeleteMessage: "Unable to delete message.",
    messageUpdated: "Message updated.",
    unableToUpdateMessage: "Unable to update message.",
    reactionAdded: "Reaction added.",
    unableToAddReaction: "Unable to add reaction.",
    reactionRemoved: "Reaction removed.",
    unableToRemoveReaction: "Unable to remove reaction.",
    attachmentUploaded: "Attachment uploaded.",
    unableToUploadAttachment: "Unable to upload attachment.",
    sendMessageBeforeAttach: "Send a message first, then attach the file to it.",
    uploadingAttachment: "Uploading attachment...",
    like: "Like",
    noMessagesYetFull: "No messages yet. Start the conversation.",
    participantUpdated: "Participant updated.",
    participantPromoted: "Participant promoted.",
    participantDemoted: "Participant demoted.",
    participantRemoved: "Participant removed.",
    conversationLeft: "Conversation left.",
    inviteAccepted: "Invite accepted.",
    inviteRejected: "Invite rejected.",
    joinRequestCreated: "Join request created.",
    you: "You",
    owner: "Owner",
    muted: "Muted",
    joined: "Joined",
    recently: "recently",
    promote: "Promote",
    demote: "Demote",
    expires: "Expires",
    noExpiration: "No expiration",
    invitedUser: "Invited user",
    requester: "Requester",
    someone: "Someone",
    participant: "Participant",
    leaveConversation: "Leave conversation",
    editParticipant: "Edit participant",
    removeParticipant: "Remove participant",
    rejectInvite: "Reject invite",
    revokeInvite: "Revoke invite",
    acceptInvite: "Accept invite",
    approveRequest: "Approve request",
    rejectRequest: "Reject request",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    approved: "Approved",
    expired: "Expired",
    active: "Active",
    readOnlyRole: "Read only",
    title: "Title",
    type: "Type",
    description: "Description",
    academicYearId: "Academic Year",
    termId: "Term",
    stageId: "Stage",
    gradeId: "Grade",
    sectionId: "Section",
    classroomId: "Classroom",
    subjectId: "Subject",
    avatarFileId: "Avatar File",
    group: "Group",
    classroom: "Classroom",
    grade: "Grade",
    section: "Section",
    stage: "Stage",
    schoolWide: "School-wide",
    support: "Support",
    titleRequired: "Enter a conversation title.",
    classroomRequired: "Select a classroom.",
    user: "User",
    role: "Role",
    status: "Status",
    mutedUntil: "Muted until",
    add: "Add",
    userRequired: "Select a user.",
    admin: "Admin",
    moderator: "Moderator",
    member: "Member",
    system: "System",
    invited: "Invited",
    left: "Left",
    removed: "Removed",
    blocked: "Blocked",
    editParticipantTitle: "Edit Participant",
    promoteParticipantTitle: "Promote Participant",
    demoteParticipantTitle: "Demote Participant",
    targetRole: "Target role",
    removeParticipantTitle: "Remove Participant",
    removeParticipantDescription: "This participant will be removed from the conversation.",
    leaveConversationTitle: "Leave Conversation",
    leaveConversationDescription:
      "You will leave this conversation and may need to be added again to rejoin.",
    expiresAt: "Expires at",
    rejectInviteTitle: "Reject Invite",
    rejectInviteDescription: "This invite will be rejected.",
    reason: "Reason",
    note: "Note",
    approveJoinRequestDescription: "This join request will be approved.",
    rejectJoinRequestDescription: "This join request will be rejected.",
    archiveConversation: "Archive",
    closeConversation: "Close",
    reopenConversation: "Reopen",
    muteConversation: "Mute notifications",
    unmuteConversation: "Unmute notifications",
    conversationArchived: "Conversation archived.",
    conversationClosed: "Conversation closed.",
    conversationReopened: "Conversation reopened.",
    conversationUpdated: "Conversation updated.",
    unableToArchiveConversation: "Unable to archive conversation.",
    unableToCloseConversation: "Unable to close conversation.",
    unableToReopenConversation: "Unable to reopen conversation.",
    unableToUpdateConversation: "Unable to update conversation.",
    archiveConversationConfirm: "Archive this conversation? It can be reopened later.",
    closeConversationConfirm: "Close this conversation? It can be reopened later.",
    moreActions: "More actions",
    reply: "Reply",
    copy: "Copy",
    report: "Report",
    messageInfo: "Info",
    readByList: "Read by",
    messageCopied: "Message copied.",
    reportSent: "Report sent.",
    unableToReport: "Unable to send report.",
    userType_platform_user: "Platform User",
    userType_organization_user: "Organization User",
    userType_school_user: "School User",
    userType_teacher: "Teacher",
    userType_parent: "Parent",
    userType_student: "Student",
    userType_guardian: "Guardian",
    userType_applicant: "Applicant",
    userType_pickup_delegate: "Pickup Delegate",
    userType_service_account: "Service Account",
    recent: "Recent",
    official: "Official",
    classType: "Class",
    readOnlyBadge: "Read-only",
    nConversations: "{n} conversations",
  },
  ar: {
    conversations: "المحادثات",
    manageSchoolCommunication: "إدارة تواصل المدرسة",
    searchConversations: "ابحث في المحادثات...",
    all: "الكل",
    mine: "محادثاتي",
    allTypes: "جميع الأنواع",
    unread: "غير مقروءة",
    pinned: "مثبتة",
    archived: "مؤرشفة",
    closed: "مغلقة",
    loadingConversations: "جاري تحميل المحادثات...",
    noConversationsFound: "لا توجد محادثات.",
    selectConversation: "اختر محادثة للبدء.",
    messages: "الرسائل",
    participants: "المشاركون",
    invites: "الدعوات",
    joinRequests: "طلبات الانضمام",
    createConversation: "إنشاء محادثة",
    editConversation: "تعديل المحادثة",
    addParticipant: "إضافة مشارك",
    createInvite: "إنشاء دعوة",
    createJoinRequest: "إنشاء طلب انضمام",
    reviewJoinRequest: "مراجعة طلب الانضمام",
    rejectJoinRequest: "رفض طلب الانضمام",
    messageSent: "تم إرسال الرسالة.",
    unableToSendMessage: "تعذر إرسال الرسالة.",
    participantAdded: "تمت إضافة المشارك.",
    inviteCreated: "تم إنشاء الدعوة.",
    joinRequestApproved: "تم قبول طلب الانضمام.",
    joinRequestRejected: "تم رفض طلب الانضمام.",
    readOnly: "للقراءة فقط",
    readOnlyConversation: "هذه المحادثة للقراءة فقط.",
    readOnlyComposer: "هذه المحادثة للقراءة فقط. يمكن للمشرفين فقط إرسال الرسائل.",
    loadingMessages: "جاري تحميل الرسائل...",
    noMessagesYet: "لا توجد رسائل بعد.",
    startConversation: "ابدأ المحادثة.",
    typing: "يكتب...",
    send: "إرسال",
    cancel: "إلغاء",
    dismiss: "إغلاق",
    save: "حفظ",
    create: "إنشاء",
    refreshConversations: "تحديث المحادثات",
    refreshConversation: "تحديث المحادثة",
    backToConversations: "العودة إلى المحادثات",
    searchMessages: "البحث في الرسائل",
    messageSearchUnavailable: "البحث في الرسائل غير متاح حالياً.",
    today: "اليوم",
    yesterday: "أمس",
    loading: "جاري التحميل...",
    untitledConversation: "محادثة بدون عنوان",
    direct: "مباشر",
    participantsCount: "مشارك",
    writeMessage: "اكتب رسالة...",
    addCaption: "أضف تعليقاً...",
    voiceNote: "رسالة صوتية",
    recording: "جاري التسجيل...",
    tapToRecord: "اضغط للتسجيل",
    attachFile: "إرفاق ملف",
    attachFileToMessage: "إرفاق ملف بالرسالة",
    attachment: "مرفق",
    emoji: "رمز تعبيري",
    sending: "جاري الإرسال",
    failed: "فشل",
    edited: "تم التعديل",
    sent: "تم الإرسال",
    readBy: "قرأها {count}",
    deleteMessageConfirm: "حذف هذه الرسالة؟",
    deleteAttachmentConfirm: "حذف هذا المرفق؟",
    deleteMessage: "حذف",
    editMessage: "تعديل",
    attachmentDeleted: "تم حذف المرفق.",
    unableToDeleteAttachment: "تعذر حذف المرفق.",
    messageDeleted: "تم حذف الرسالة.",
    unableToDeleteMessage: "تعذر حذف الرسالة.",
    messageUpdated: "تم تحديث الرسالة.",
    unableToUpdateMessage: "تعذر تحديث الرسالة.",
    reactionAdded: "تمت إضافة التفاعل.",
    unableToAddReaction: "تعذر إضافة التفاعل.",
    reactionRemoved: "تم حذف التفاعل.",
    unableToRemoveReaction: "تعذر حذف التفاعل.",
    attachmentUploaded: "تم رفع المرفق.",
    unableToUploadAttachment: "تعذر رفع المرفق.",
    sendMessageBeforeAttach: "أرسل رسالة أولاً، ثم أرفق الملف بها.",
    uploadingAttachment: "جاري رفع المرفق...",
    like: "إعجاب",
    noMessagesYetFull: "لا توجد رسائل بعد. ابدأ المحادثة.",
    participantUpdated: "تم تحديث المشارك.",
    participantPromoted: "تمت ترقية المشارك.",
    participantDemoted: "تم تخفيض دور المشارك.",
    participantRemoved: "تم حذف المشارك.",
    conversationLeft: "تمت مغادرة المحادثة.",
    inviteAccepted: "تم قبول الدعوة.",
    inviteRejected: "تم رفض الدعوة.",
    joinRequestCreated: "تم إنشاء طلب الانضمام.",
    you: "أنت",
    owner: "المالك",
    muted: "مكتوم",
    joined: "انضم",
    recently: "مؤخراً",
    promote: "ترقية",
    demote: "تخفيض",
    expires: "تنتهي",
    noExpiration: "بلا تاريخ انتهاء",
    invitedUser: "المستخدم المدعو",
    requester: "مقدم الطلب",
    someone: "شخص ما",
    participant: "مشارك",
    leaveConversation: "مغادرة المحادثة",
    editParticipant: "تعديل المشارك",
    removeParticipant: "حذف المشارك",
    rejectInvite: "رفض الدعوة",
    revokeInvite: "إلغاء الدعوة",
    acceptInvite: "قبول الدعوة",
    approveRequest: "قبول الطلب",
    rejectRequest: "رفض الطلب",
    pending: "قيد الانتظار",
    accepted: "مقبولة",
    rejected: "مرفوضة",
    approved: "مقبولة",
    expired: "منتهية",
    active: "نشط",
    readOnlyRole: "للقراءة فقط",
    title: "العنوان",
    type: "النوع",
    description: "الوصف",
    academicYearId: "السنة الدراسية",
    termId: "الفصل الدراسي",
    stageId: "المرحلة",
    gradeId: "الصف",
    sectionId: "القسم",
    classroomId: "الفصل",
    subjectId: "المادة",
    avatarFileId: "ملف الصورة",
    group: "مجموعة",
    classroom: "فصل",
    grade: "صف",
    section: "قسم",
    stage: "مرحلة",
    schoolWide: "كل المدرسة",
    support: "دعم",
    titleRequired: "أدخل عنوان المحادثة.",
    classroomRequired: "اختر فصلاً.",
    user: "المستخدم",
    role: "الدور",
    status: "الحالة",
    mutedUntil: "مكتوم حتى",
    add: "إضافة",
    userRequired: "اختر مستخدماً.",
    admin: "مسؤول",
    moderator: "مشرف",
    member: "عضو",
    system: "نظام",
    invited: "مدعو",
    left: "غادر",
    removed: "محذوف",
    blocked: "محظور",
    editParticipantTitle: "تعديل المشارك",
    promoteParticipantTitle: "ترقية المشارك",
    demoteParticipantTitle: "تخفيض المشارك",
    targetRole: "الدور المستهدف",
    removeParticipantTitle: "حذف المشارك",
    removeParticipantDescription: "سيتم حذف هذا المشارك من المحادثة.",
    leaveConversationTitle: "مغادرة المحادثة",
    leaveConversationDescription:
      "ستغادر هذه المحادثة وقد تحتاج إلى إضافتك مرة أخرى للانضمام.",
    expiresAt: "تنتهي في",
    rejectInviteTitle: "رفض الدعوة",
    rejectInviteDescription: "سيتم رفض هذه الدعوة.",
    reason: "السبب",
    note: "ملاحظة",
    approveJoinRequestDescription: "سيتم قبول طلب الانضمام هذا.",
    rejectJoinRequestDescription: "سيتم رفض طلب الانضمام هذا.",
    archiveConversation: "أرشفة",
    closeConversation: "إغلاق",
    reopenConversation: "إعادة فتح",
    muteConversation: "كتم الإشعارات",
    unmuteConversation: "تفعيل الإشعارات",
    conversationArchived: "تم أرشفة المحادثة.",
    conversationClosed: "تم إغلاق المحادثة.",
    conversationReopened: "تم إعادة فتح المحادثة.",
    conversationUpdated: "تم تحديث المحادثة.",
    unableToArchiveConversation: "تعذر أرشفة المحادثة.",
    unableToCloseConversation: "تعذر إغلاق المحادثة.",
    unableToReopenConversation: "تعذر إعادة فتح المحادثة.",
    unableToUpdateConversation: "تعذر تحديث المحادثة.",
    archiveConversationConfirm: "أرشفة هذه المحادثة؟ يمكن إعادة فتحها لاحقاً.",
    closeConversationConfirm: "إغلاق هذه المحادثة؟ يمكن إعادة فتحها لاحقاً.",
    moreActions: "المزيد",
    reply: "رد",
    copy: "نسخ",
    report: "إبلاغ",
    messageInfo: "معلومات",
    readByList: "قرأها",
    messageCopied: "تم نسخ الرسالة.",
    reportSent: "تم إرسال البلاغ.",
    unableToReport: "تعذر إرسال البلاغ.",
    unableToCreateConversation: "تعذر إنشاء المحادثة.",
    unableToAddParticipant: "تعذر إضافة المشارك.",
    unableToUpdateParticipant: "تعذر تحديث المشارك.",
    unableToPromoteParticipant: "تعذر ترقية المشارك.",
    unableToDemoteParticipant: "تعذر تخفيض دور المشارك.",
    unableToRemoveParticipant: "تعذر حذف المشارك.",
    unableToLeaveConversation: "تعذر مغادرة المحادثة.",
    unableToCreateInvite: "تعذر إنشاء الدعوة.",
    unableToAcceptInvite: "تعذر قبول الدعوة.",
    unableToRejectInvite: "تعذر رفض الدعوة.",
    unableToCreateJoinRequest: "تعذر إنشاء طلب الانضمام.",
    unableToApproveJoinRequest: "تعذر قبول طلب الانضمام.",
    unableToRejectJoinRequest: "تعذر رفض طلب الانضمام.",
    userType_platform_user: "مستخدم المنصة",
    userType_organization_user: "مستخدم المؤسسة",
    userType_school_user: "مستخدم المدرسة",
    userType_teacher: "معلم",
    userType_parent: "ولي أمر",
    userType_student: "طالب",
    userType_guardian: "ولي أمر",
    userType_applicant: "متقدم",
    userType_pickup_delegate: "مفوض استلام",
    userType_service_account: "حساب خدمة",
    recent: "الأحدث",
    official: "رسمي",
    classType: "فصل",
    readOnlyBadge: "للقراءة فقط",
    nConversations: "{n} محادثة",
  },
} as const;

export type ConversationRedesignLabels =
  (typeof conversationRedesignLabels)[ConversationRedesignLocale];

export function labelsForLocale(locale: string): ConversationRedesignLabels {
  return locale === "ar" ? conversationRedesignLabels.ar : conversationRedesignLabels.en;
}
