import type { PermissionDefinition } from "@/features/settings/types";

export const permissionCatalog: PermissionDefinition[] = [
  {
    key: "settings.overview.view",
    module: "overview",
    action: "view",
    label: "Settings overview",
    description: "View settings health, invites, integrations, and audit summary.",
  },
  {
    key: "settings.branding.view",
    module: "branding",
    action: "view",
    label: "View branding & profile",
    description: "Access school profile and branding settings.",
  },
  {
    key: "settings.branding.manage",
    module: "branding",
    action: "manage",
    label: "Manage branding & profile",
    description: "Edit school profile, logo, and footer branding.",
  },
  {
    key: "settings.users.view",
    module: "users",
    action: "view",
    label: "View users",
    description: "Access users and invitations listing.",
  },
  {
    key: "settings.users.manage",
    module: "users",
    action: "manage",
    label: "Manage users",
    description: "Create users, resend invites, change status, and assign roles.",
  },
  {
    key: "settings.roles.view",
    module: "roles",
    action: "view",
    label: "View roles & permissions",
    description: "Access role assignments and permission matrix.",
  },
  {
    key: "settings.roles.manage",
    module: "roles",
    action: "manage",
    label: "Manage roles & permissions",
    description: "Create, clone, edit, and remove custom roles.",
  },
  {
    key: "settings.policies.view",
    module: "policies",
    action: "view",
    label: "View policies",
    description: "Access attendance, grade, and discipline policies.",
  },
  {
    key: "settings.policies.manage",
    module: "policies",
    action: "manage",
    label: "Manage policies",
    description: "Configure attendance, grading, and discipline policies.",
  },
  {
    key: "settings.admissionsDocuments.view",
    module: "admissions_documents",
    action: "view",
    label: "View admissions documents settings",
    description: "Access the school-wide admissions document requirement list.",
  },
  {
    key: "settings.admissionsDocuments.manage",
    module: "admissions_documents",
    action: "manage",
    label: "Manage admissions documents settings",
    description: "Create, edit, reorder, activate, and remove admissions document requirements.",
  },
  {
    key: "settings.templates.view",
    module: "templates",
    action: "view",
    label: "View notification templates",
    description: "Review template coverage, channels, and variables.",
  },
  {
    key: "settings.templates.manage",
    module: "templates",
    action: "manage",
    label: "Manage notification templates",
    description: "Edit messages, channels, and variables for templates.",
  },
  {
    key: "settings.integrations.view",
    module: "integrations",
    action: "view",
    label: "View integrations",
    description: "Review provider health and connection state.",
  },
  {
    key: "settings.integrations.configure",
    module: "integrations",
    action: "configure",
    label: "Configure integrations",
    description: "Edit provider configuration and run connection tests.",
  },
  {
    key: "settings.security.view",
    module: "security",
    action: "view",
    label: "View security & audit",
    description: "Access security controls and audit logs.",
  },
  {
    key: "settings.security.manage",
    module: "security",
    action: "manage",
    label: "Manage security & audit",
    description: "Update security controls and export or review sensitive logs.",
  },
  {
    key: "settings.backup.view",
    module: "backup",
    action: "view",
    label: "View backup & migration",
    description: "Access backup history and migration tooling.",
  },
  {
    key: "settings.backup.manage",
    module: "backup",
    action: "manage",
    label: "Manage backup & migration",
    description: "Run exports, imports, backup jobs, and migration actions.",
  },
  {
    key: "nedaa.overview.view",
    module: "nedaa",
    action: "view",
    label: "View Nedaa overview",
    description: "Access Nedaa overview metrics, gate summaries, and live pickup KPIs.",
  },
  {
    key: "nedaa.requests.view",
    module: "nedaa",
    action: "view",
    label: "View Nedaa requests",
    description: "Access live pickup requests, gate boards, and request history.",
  },
  {
    key: "nedaa.requests.manage",
    module: "nedaa",
    action: "manage",
    label: "Manage Nedaa requests",
    description: "Acknowledge, prepare, complete, and cancel Nedaa pickup requests.",
  },
  {
    key: "nedaa.settings.view",
    module: "nedaa",
    action: "view",
    label: "View Nedaa settings",
    description: "Access Nedaa operational rules, pickup windows, and gate configuration.",
  },
  {
    key: "nedaa.settings.manage",
    module: "nedaa",
    action: "manage",
    label: "Manage Nedaa settings",
    description: "Update Nedaa operational rules, default gate selection, and gate setup.",
  },
];