import type { PermissionDefinition } from "@/features/settings/types";

export const permissionCatalog: PermissionDefinition[] = [
  {
    key: "admissions.applications.view",
    module: "admissions_applications",
    action: "view",
    label: "View admissions applications",
    description: "Access admissions application lists and application details.",
  },
  {
    key: "admissions.applications.manage",
    module: "admissions_applications",
    action: "manage",
    label: "Manage admissions applications",
    description: "Create, submit, review, and update admissions applications.",
  },
  {
    key: "admissions.documents.view",
    module: "admissions_documents",
    action: "view",
    label: "View admissions applicant documents",
    description: "Access and download documents submitted by applicants.",
  },
  {
    key: "admissions.documents.manage",
    module: "admissions_documents",
    action: "manage",
    label: "Manage admissions applicant documents",
    description:
      "Upload, remove, accept, reject, and request replacements for applicant documents.",
  },
  {
    key: "settings.overview.view",
    module: "overview",
    action: "view",
    label: "Settings overview",
    description:
      "View settings health, invites, integrations, and audit summary.",
  },
  {
    key: "settings.branding.view",
    module: "branding",
    action: "view",
    label: "View branding & profile",
    description: "Access school profile and branding settings.",
  },
  {
    key: "settings.branding.manage",
    module: "branding",
    action: "manage",
    label: "Manage branding & profile",
    description: "Edit school profile, logo, and footer branding.",
  },
  {
    key: "settings.users.view",
    module: "users",
    action: "view",
    label: "View users",
    description: "Access users and invitations listing.",
  },
  {
    key: "settings.users.manage",
    module: "users",
    action: "manage",
    label: "Manage users",
    description:
      "Create users, resend invites, change status, and assign roles.",
  },
  {
    key: "settings.roles.view",
    module: "roles",
    action: "view",
    label: "View roles & permissions",
    description: "Access role assignments and permission matrix.",
  },
  {
    key: "settings.roles.manage",
    module: "roles",
    action: "manage",
    label: "Manage roles & permissions",
    description: "Create, clone, edit, and remove custom roles.",
  },
  {
    key: "settings.permissions.view",
    module: "permissions",
    action: "view",
    label: "View permission catalog",
    description: "Access the settings permission catalog.",
  },
  {
    key: "settings.policies.view",
    module: "policies",
    action: "view",
    label: "View policies",
    description: "Access attendance, grade, and discipline policies.",
  },
  {
    key: "settings.policies.manage",
    module: "policies",
    action: "manage",
    label: "Manage policies",
    description: "Configure attendance, grading, and discipline policies.",
  },
  {
    key: "settings.admissionsDocuments.view",
    module: "admissions_documents",
    action: "view",
    label: "View admissions documents settings",
    description: "Access the school-wide admissions document requirement list.",
  },
  {
    key: "settings.admissionsDocuments.manage",
    module: "admissions_documents",
    action: "manage",
    label: "Manage admissions documents settings",
    description:
      "Create, edit, reorder, activate, and remove admissions document requirements.",
  },
  {
    key: "settings.templates.view",
    module: "templates",
    action: "view",
    label: "View notification templates",
    description: "Review template coverage, channels, and variables.",
  },
  {
    key: "settings.templates.manage",
    module: "templates",
    action: "manage",
    label: "Manage notification templates",
    description: "Edit messages, channels, and variables for templates.",
  },
  {
    key: "settings.integrations.view",
    module: "integrations",
    action: "view",
    label: "View integrations",
    description: "Review provider health and connection state.",
  },
  {
    key: "settings.integrations.configure",
    module: "integrations",
    action: "configure",
    label: "Configure integrations",
    description: "Edit provider configuration and run connection tests.",
  },
  {
    key: "settings.email.connection.view",
    module: "email",
    action: "view",
    label: "View email connection",
    description: "Access the school email provider connection.",
  },
  {
    key: "settings.email.connection.manage",
    module: "email",
    action: "manage",
    label: "Manage email connection",
    description: "Configure, test, activate, and disable the email provider.",
  },
  {
    key: "settings.email.templates.view",
    module: "email",
    action: "view",
    label: "View email templates",
    description: "Access and preview email templates.",
  },
  {
    key: "settings.email.templates.manage",
    module: "email",
    action: "manage",
    label: "Manage email templates",
    description: "Update and reset email templates.",
  },
  {
    key: "settings.email.credential_deliveries.view",
    module: "email",
    action: "view",
    label: "View credential deliveries",
    description: "Preview recipients for credential delivery batches.",
  },
  {
    key: "settings.email.credential_deliveries.manage",
    module: "email",
    action: "manage",
    label: "Manage credential deliveries",
    description: "Create credential delivery batches.",
  },
  {
    key: "settings.email.deliveries.view",
    module: "email",
    action: "view",
    label: "View email deliveries",
    description: "Access email delivery batches and recipients.",
  },
  {
    key: "settings.email.deliveries.manage",
    module: "email",
    action: "manage",
    label: "Manage email deliveries",
    description: "Cancel queued email delivery batches.",
  },
  {
    key: "settings.email.campaigns.view",
    module: "email",
    action: "view",
    label: "View email campaigns",
    description: "Access and preview email campaigns.",
  },
  {
    key: "settings.email.campaigns.manage",
    module: "email",
    action: "manage",
    label: "Manage email campaigns",
    description: "Create email campaign batches.",
  },
  {
    key: "settings.security.view",
    module: "security",
    action: "view",
    label: "View security & audit",
    description: "Access security controls and audit logs.",
  },
  {
    key: "settings.security.manage",
    module: "security",
    action: "manage",
    label: "Manage security & audit",
    description:
      "Update security controls and export or review sensitive logs.",
  },
  {
    key: "settings.backup.view",
    module: "backup",
    action: "view",
    label: "View backup & migration",
    description: "Access backup history and migration tooling.",
  },
  {
    key: "settings.backup.manage",
    module: "backup",
    action: "manage",
    label: "Manage backup & migration",
    description: "Run exports, imports, backup jobs, and migration actions.",
  },
  {
    key: "dismissal.settings.view",
    module: "nedaa",
    action: "view",
    label: "View dismissal settings",
    description: "Access backend dismissal settings.",
  },
  {
    key: "dismissal.settings.manage",
    module: "nedaa",
    action: "manage",
    label: "Manage dismissal settings",
    description: "Update backend dismissal settings.",
  },
  {
    key: "dismissal.gates.view",
    module: "nedaa",
    action: "view",
    label: "View dismissal gates",
    description: "Access backend dismissal gates.",
  },
  {
    key: "dismissal.gates.manage",
    module: "nedaa",
    action: "manage",
    label: "Manage dismissal gates",
    description: "Create and update backend dismissal gates.",
  },
  {
    key: "dismissal.staff.view",
    module: "nedaa",
    action: "view",
    label: "View dismissal staff assignments",
    description: "Access backend dismissal staff assignments.",
  },
  {
    key: "dismissal.staff.manage",
    module: "nedaa",
    action: "manage",
    label: "Manage dismissal staff assignments",
    description: "Create, update, and delete backend dismissal staff assignments.",
  },
  {
    key: "dismissal.requests.view",
    module: "nedaa",
    action: "view",
    label: "View dismissal operations",
    description: "Access active dismissal requests and waiting students.",
  },
  {
    key: "dismissal.requests.manage",
    module: "nedaa",
    action: "manage",
    label: "Manage dismissal operations",
    description: "Update request statuses and confirm student arrivals.",
  },
  {
    key: "dismissal.requests.deliver",
    module: "nedaa",
    action: "manage",
    label: "Deliver dismissal requests",
    description: "Verify pickup recipients and complete student handovers.",
  },
  {
    key: "dismissal.requests.escalate",
    module: "nedaa",
    action: "manage",
    label: "Escalate dismissal requests",
    description: "Escalate active dismissal requests for follow-up.",
  },
  {
    key: "dismissal.requests.history.view",
    module: "nedaa",
    action: "view",
    label: "View dismissal request history",
    description: "Access completed and historical dismissal requests.",
  },
  {
    key: "academics.structure.view",
    module: "academics",
    action: "view",
    label: "View Academic Structure",
    description: "View academic years, terms, stages, and structure.",
  },
  {
    key: "academics.structure.manage",
    module: "academics",
    action: "manage",
    label: "Manage Academic Structure",
    description:
      "Create and edit academic years, terms, and the structure tree.",
  },
];
